export { parseXml, scanXml, serializeXml } from "./xml-parser.js"
export { Visit } from "./xml-parser.js"
export type { XmlCursor, XmlSink } from "./xml-parser.js"
export { parseXmlSpans } from "./xml-spans.js"
export type { SpannedAttribute, SpannedElement } from "./xml-spans.js"
export { preserveFormatting, preserveFormattingVerified } from "./xml-patch.js"
export type { PreserveOptions, SiblingOrder, VerifiedPreserve } from "./xml-patch.js"
