packages:
  - packages/*
  - apps/*
  - plugins-cli/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - sharp
  - workerd

patchedDependencies:
  '@preact/signals-react@2.3.0': patches/@preact__signals-react@2.3.0.patch
