/**
 * Typed code generation from BPMN — the contract between a process model and
 * the job workers, message publishers and error throwers written against it.
 *
 * {@link extractProcessContract} reads what a set of definitions promises
 * (process ids, job types with their variables and headers, message / signal /
 * error / escalation names) and {@link generateProcessTypes} renders it as
 * TypeScript source.
 *
 * The types are necessarily approximate — FEEL cannot be fully typed — so
 * every value is `unknown`, but the keys are exact. The rules:
 *
 * - **Jobs** are every element carrying `zeebe:taskDefinition` with a static
 *   type: service, send, script and business rule tasks implemented by a job
 *   worker, message throw events, and ad-hoc sub-processes (AI Agent job
 *   workers). User tasks are left out: Camunda user tasks have no job, and
 *   job-based user tasks all share the engine's own type. A type written as a
 *   FEEL expression (`=…`) is dynamic and is skipped.
 * - **Variables** (what the worker receives): the targets of the element's
 *   `zeebe:input` mappings, all required. With no input mappings, the
 *   variables the variable-flow analysis finds in scope on the element's
 *   incoming flows (other elements' input targets are local to them and left
 *   out), all optional.
 * - **Output** (what the worker should complete with): the root variables the
 *   element's `zeebe:output` sources read, minus its own input targets —
 *   required when the source is a plain reference (`=total`), optional
 *   otherwise. With no output mappings, the variables read downstream that
 *   nothing in the process sets, all optional.
 * - **Headers**: `zeebe:taskHeaders` with their literal values; a key missing
 *   from some of the elements sharing the job type is optional.
 * - **Errors** a job can throw: the codes caught by error boundary events on the
 *   element or its enclosing sub-processes, and by error event sub-processes in
 *   those scopes. A catch-all error event widens this to `string`; no catch at
 *   all gives `never` (an uncaught error raises an incident).
 * - Elements sharing a job type are merged: a key is required only when every
 *   element requires it.
 * - Only executable processes (`isExecutable="true"`) are read.
 */
import type {
	BpmnDefinitions,
	BpmnEventDefinition,
	BpmnFlowElement,
	BpmnProcess,
	BpmnSequenceFlow,
} from "./bpmn-model.js"
import {
	buildFlowIndex,
	reachableFrom,
	readZeebeIoMapping,
	readZeebeTaskHeaders,
	readZeebeTaskType,
} from "./optimize/utils.js"
import { analyzeVariableFlow, extractFeelIdentifiers } from "./optimize/variable-flow.js"

// ---------------------------------------------------------------------------
// Contract model
// ---------------------------------------------------------------------------

/** A variable key in a job contract. */
export interface ContractVariable {
	name: string
	/** False when the model does not guarantee the key is present. */
	required: boolean
}

/** A task header key and the literal values it takes across elements. */
export interface ContractHeader {
	key: string
	values: string[]
	required: boolean
}

/** Where a job type, message, signal, error or escalation is used. */
export interface ContractElementRef {
	processId: string
	elementId: string
	elementType: BpmnFlowElement["type"]
}

/** Everything a worker for one job type can rely on. */
export interface JobContract {
	type: string
	elements: ContractElementRef[]
	variables: ContractVariable[]
	output: ContractVariable[]
	headers: ContractHeader[]
	/** Error codes a worker may throw and have caught; `"any"` when a catch-all exists. */
	errors: string[] | "any"
}

/** A message name and the correlation keys its catch events subscribe with. */
export interface MessageContract {
	name: string
	correlationKeys: string[]
	elements: ContractElementRef[]
}

/** A signal name, error code or escalation code. */
export interface CodeContract {
	code: string
	elements: ContractElementRef[]
}

/** The contract a set of BPMN definitions promises its workers and clients. */
export interface ProcessContract {
	processIds: string[]
	jobs: JobContract[]
	messages: MessageContract[]
	signals: CodeContract[]
	errors: CodeContract[]
	escalations: CodeContract[]
	/** Job types written as FEEL expressions — resolved at runtime, so not typed. */
	dynamicJobTypes: ContractElementRef[]
}

/** Options for {@link generateProcessTypes}. */
export interface ProcessTypesOptions {
	/** First line of the header comment. Default: "generated by casen gen types — do not edit". */
	banner?: string
}

// ---------------------------------------------------------------------------
// Extraction
// ---------------------------------------------------------------------------

interface Container {
	flowElements: BpmnFlowElement[]
	sequenceFlows: BpmnSequenceFlow[]
}

interface Scope {
	/** The enclosing sub-processes, innermost first (the process itself is not included). */
	ancestors: BpmnFlowElement[]
	container: Container
}

interface JobAccumulator {
	elements: ContractElementRef[]
	variables: Map<string, boolean>[]
	output: Map<string, boolean>[]
	headers: Map<string, string>[]
	errors: Set<string>
	anyError: boolean
}

function isContainer(el: BpmnFlowElement): el is BpmnFlowElement & Container {
	return (
		el.type === "subProcess" ||
		el.type === "adHocSubProcess" ||
		el.type === "eventSubProcess" ||
		el.type === "transaction"
	)
}

function eventDefinitions(el: BpmnFlowElement): BpmnEventDefinition[] {
	return "eventDefinitions" in el ? el.eventDefinitions : []
}

const isDynamic = (value: string): boolean => value.trim().startsWith("=")

function addRef(
	map: Map<string, ContractElementRef[]>,
	key: string,
	ref: ContractElementRef,
): void {
	const list = map.get(key)
	if (list) list.push(ref)
	else map.set(key, [ref])
}

const byText = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0)

const byRef = (a: ContractElementRef, b: ContractElementRef): number =>
	byText(a.processId, b.processId) || byText(a.elementId, b.elementId)

function uniqueRefs(refs: ContractElementRef[]): ContractElementRef[] {
	const seen = new Set<string>()
	const out: ContractElementRef[] = []
	for (const ref of [...refs].sort(byRef)) {
		const key = `${ref.processId}\u0000${ref.elementId}`
		if (seen.has(key)) continue
		seen.add(key)
		out.push(ref)
	}
	return out
}

/** Merge per-element key maps: a key is required only when every element requires it. */
function mergeKeys(maps: Map<string, boolean>[]): ContractVariable[] {
	const names = new Set<string>()
	for (const map of maps) for (const name of map.keys()) names.add(name)
	return [...names].sort(byText).map((name) => ({
		name,
		required: maps.every((map) => map.get(name) === true),
	}))
}

function readSubscriptionKey(
	ext: ReadonlyArray<{ name: string; attributes: Record<string, string> }>,
): string | undefined {
	const sub = ext.find((e) => e.name === "zeebe:subscription")
	const key = sub?.attributes.correlationKey?.trim()
	return key === undefined || key === "" ? undefined : key
}

/**
 * Read the worker-facing contract out of one or more BPMN definitions. Pure and
 * deterministic: every list is sorted.
 */
export function extractProcessContract(
	definitions: BpmnDefinitions | readonly BpmnDefinitions[],
): ProcessContract {
	const all: readonly BpmnDefinitions[] = Array.isArray(definitions)
		? definitions
		: [definitions as BpmnDefinitions]

	const processIds = new Set<string>()
	const jobs = new Map<string, JobAccumulator>()
	const dynamicJobTypes: ContractElementRef[] = []
	const messageRefs = new Map<string, ContractElementRef[]>()
	const messageKeys = new Map<string, Set<string>>()
	const signals = new Map<string, ContractElementRef[]>()
	const errors = new Map<string, ContractElementRef[]>()
	const escalations = new Map<string, ContractElementRef[]>()

	for (const defs of all) {
		const errorById = new Map(defs.errors.map((e) => [e.id, e]))
		const escalationById = new Map(defs.escalations.map((e) => [e.id, e]))
		const messageById = new Map(defs.messages.map((m) => [m.id, m]))
		const signalById = new Map(defs.signals.map((s) => [s.id, s]))

		for (const process of defs.processes) {
			if (process.isExecutable !== true) continue
			processIds.add(process.id)
			const flow = variableFlowIndex(process)
			const topIndex = buildFlowIndex(process)

			/** Error codes caught at a scope (boundary on `el`, or error event sub-processes inside `container`). */
			const caughtIn = (
				scopeElement: BpmnFlowElement | undefined,
				container: Container,
			): { codes: string[]; any: boolean } => {
				const codes: string[] = []
				let any = false
				const collect = (defsList: BpmnEventDefinition[]): void => {
					for (const def of defsList) {
						if (def.type !== "error") continue
						const code =
							def.errorRef === undefined ? undefined : errorById.get(def.errorRef)?.errorCode
						if (code === undefined || code.trim() === "") any = true
						else codes.push(code)
					}
				}
				if (scopeElement !== undefined) {
					for (const el of container.flowElements) {
						if (el.type === "boundaryEvent" && el.attachedToRef === scopeElement.id) {
							collect(el.eventDefinitions)
						}
					}
				}
				return { codes, any }
			}
			const eventSubProcessCatches = (container: Container): { codes: string[]; any: boolean } => {
				const codes: string[] = []
				let any = false
				for (const el of container.flowElements) {
					const isEventSub =
						el.type === "eventSubProcess" || (el.type === "subProcess" && el.triggeredByEvent)
					if (!isEventSub || !isContainer(el)) continue
					for (const start of el.flowElements) {
						if (start.type !== "startEvent") continue
						for (const def of start.eventDefinitions) {
							if (def.type !== "error") continue
							const code =
								def.errorRef === undefined ? undefined : errorById.get(def.errorRef)?.errorCode
							if (code === undefined || code.trim() === "") any = true
							else codes.push(code)
						}
					}
				}
				return { codes, any }
			}

			const visit = (container: Container, ancestors: BpmnFlowElement[]): void => {
				for (const el of container.flowElements) {
					const ref: ContractElementRef = {
						processId: process.id,
						elementId: el.id,
						elementType: el.type,
					}
					collectEvents(el, ref)

					const jobType = el.type === "userTask" ? null : readZeebeTaskType(el.extensionElements)
					if (jobType !== null && jobType.trim() !== "") {
						if (isDynamic(jobType)) dynamicJobTypes.push(ref)
						else addJob(jobType, el, ref, { ancestors, container })
					}

					if (isContainer(el)) visit(el, [el, ...ancestors])
				}
			}

			const collectEvents = (el: BpmnFlowElement, ref: ContractElementRef): void => {
				const messageRefIds: string[] = []
				if ((el.type === "sendTask" || el.type === "receiveTask") && el.messageRef) {
					messageRefIds.push(el.messageRef)
				}
				for (const def of eventDefinitions(el)) {
					if (def.type === "message" && def.messageRef) messageRefIds.push(def.messageRef)
					if (def.type === "signal" && def.signalRef) {
						const name = signalById.get(def.signalRef)?.name
						if (name && !isDynamic(name)) addRef(signals, name, ref)
					}
					if (def.type === "error" && def.errorRef) {
						const code = errorById.get(def.errorRef)?.errorCode
						if (code && !isDynamic(code)) addRef(errors, code, ref)
					}
					if (def.type === "escalation" && def.escalationRef) {
						const code = escalationById.get(def.escalationRef)?.escalationCode
						if (code && !isDynamic(code)) addRef(escalations, code, ref)
					}
				}
				for (const id of messageRefIds) {
					const message = messageById.get(id)
					const name = message?.name
					if (!name || isDynamic(name)) continue
					addRef(messageRefs, name, ref)
					const key =
						readSubscriptionKey(el.extensionElements) ??
						readSubscriptionKey(message.extensionElements ?? [])
					const keys = messageKeys.get(name) ?? new Set<string>()
					if (key !== undefined) keys.add(key)
					messageKeys.set(name, keys)
				}
			}

			const addJob = (
				jobType: string,
				el: BpmnFlowElement,
				ref: ContractElementRef,
				scope: Scope,
			): void => {
				const acc: JobAccumulator = jobs.get(jobType) ?? {
					elements: [],
					variables: [],
					output: [],
					headers: [],
					errors: new Set(),
					anyError: false,
				}
				jobs.set(jobType, acc)
				acc.elements.push(ref)

				const io = readZeebeIoMapping(el.extensionElements)
				const inputTargets = (io?.inputs ?? [])
					.map((input) => input.target.trim())
					.filter((target) => target !== "")

				const variables = new Map<string, boolean>()
				if (inputTargets.length > 0) {
					for (const target of inputTargets) variables.set(target, true)
				} else {
					for (const name of flow.scopeBefore(el, scope)) variables.set(name, false)
				}
				acc.variables.push(variables)

				const output = new Map<string, boolean>()
				const outputs = (io?.outputs ?? []).filter((o) => o.target.trim() !== "")
				if (outputs.length > 0) {
					const locals = new Set(inputTargets)
					for (const mapping of outputs) {
						const plain = /^=?\s*[A-Za-z_$][\w$]*(\s*\.\s*[A-Za-z_$][\w$]*)*\s*$/.test(
							mapping.source,
						)
						for (const name of extractFeelIdentifiers(mapping.source)) {
							if (locals.has(name)) continue
							output.set(name, (output.get(name) ?? false) || plain)
						}
					}
				} else if (scope.ancestors.length === 0) {
					const downstream = reachableFrom(
						topIndex.bySource.get(el.id)?.map((f) => f.targetRef) ?? [],
						topIndex.bySource,
					)
					for (const id of [...downstream].sort(byText)) {
						if (id === el.id) continue
						for (const name of flow.consumedBy.get(id) ?? []) {
							if (!flow.produced.has(name)) output.set(name, false)
						}
					}
				}
				acc.output.push(output)

				const headers = new Map<string, string>()
				for (const header of readZeebeTaskHeaders(el.extensionElements)?.headers ?? []) {
					if (header.key !== "") headers.set(header.key, header.value)
				}
				acc.headers.push(headers)

				const scopes: Array<{ element: BpmnFlowElement | undefined; container: Container }> = [
					{ element: el, container: scope.container },
				]
				let containerOf: Container = process
				for (let i = scope.ancestors.length - 1; i >= 0; i--) {
					const ancestor = scope.ancestors[i] as BpmnFlowElement
					scopes.push({ element: ancestor, container: containerOf })
					if (isContainer(ancestor)) containerOf = ancestor
				}
				const catches = [
					...scopes.map((s) => caughtIn(s.element, s.container)),
					eventSubProcessCatches(process),
					...scope.ancestors.filter(isContainer).map(eventSubProcessCatches),
				]
				for (const c of catches) {
					for (const code of c.codes) acc.errors.add(code)
					if (c.any) acc.anyError = true
				}
			}

			visit(process, [])
		}
	}

	const jobList: JobContract[] = [...jobs.entries()]
		.sort(([a], [b]) => byText(a, b))
		.map(([type, acc]) => {
			const headerKeys = new Set<string>()
			for (const map of acc.headers) for (const key of map.keys()) headerKeys.add(key)
			return {
				type,
				elements: uniqueRefs(acc.elements),
				variables: mergeKeys(acc.variables),
				output: mergeKeys(acc.output),
				headers: [...headerKeys].sort(byText).map((key) => {
					const values = new Set<string>()
					for (const map of acc.headers) {
						const value = map.get(key)
						if (value !== undefined) values.add(value)
					}
					return {
						key,
						values: [...values].sort(byText),
						required: acc.headers.every((map) => map.has(key)),
					}
				}),
				errors: acc.anyError ? "any" : [...acc.errors].sort(byText),
			}
		})

	const codes = (map: Map<string, ContractElementRef[]>): CodeContract[] =>
		[...map.entries()]
			.sort(([a], [b]) => byText(a, b))
			.map(([code, refs]) => ({ code, elements: uniqueRefs(refs) }))

	return {
		processIds: [...processIds].sort(byText),
		jobs: jobList,
		messages: [...messageRefs.entries()]
			.sort(([a], [b]) => byText(a, b))
			.map(([name, refs]) => ({
				name,
				correlationKeys: [...(messageKeys.get(name) ?? [])].sort(byText),
				elements: uniqueRefs(refs),
			})),
		signals: codes(signals),
		errors: codes(errors),
		escalations: codes(escalations),
		dynamicJobTypes: uniqueRefs(dynamicJobTypes),
	}
}

/** What the variable-flow analysis knows about one process, indexed for lookup. */
function variableFlowIndex(process: BpmnProcess) {
	// The analysis counts `zeebe:input` targets as produced, but they are local to
	// their element: nothing downstream sees one unless something else also sets it.
	const inputTargets = new Set<string>()
	const setGlobally = new Set<string>()
	for (const el of process.flowElements) {
		const io = readZeebeIoMapping(el.extensionElements)
		for (const input of io?.inputs ?? []) inputTargets.add(input.target.trim())
		for (const output of io?.outputs ?? []) setGlobally.add(output.target.trim())
		for (const ext of el.extensionElements) {
			const result = ext.attributes.resultVariable
			if (ext.name === "zeebe:calledDecision" && result) setGlobally.add(result)
		}
	}
	const visible = (name: string): boolean => !inputTargets.has(name) || setGlobally.has(name)

	const edgeScope = new Map<string, string[]>()
	const consumedBy = new Map<string, string[]>()
	const produced = new Set<string>()
	for (const f of analyzeVariableFlow(process)) {
		if (f.id.startsWith("data-flow/edge-scope:")) {
			const flowId = f.elementIds[0]
			if (flowId !== undefined) edgeScope.set(flowId, (f.produces ?? []).filter(visible))
		} else if (f.id.startsWith("data-flow/role:")) {
			const elementId = f.elementIds[0]
			if (elementId !== undefined) consumedBy.set(elementId, f.consumes ?? [])
			for (const name of f.produces ?? []) if (visible(name)) produced.add(name)
		}
	}
	return {
		consumedBy,
		produced,
		/**
		 * Variables in scope on the element's incoming flows — or, for an element
		 * with none known, on the incoming flows of its nearest enclosing scope.
		 */
		scopeBefore(el: BpmnFlowElement, scope: Scope): string[] {
			for (const candidate of [el, ...scope.ancestors]) {
				const names = new Set<string>()
				let known = false
				for (const flowId of candidate.incoming) {
					const vars = edgeScope.get(flowId)
					if (vars === undefined) continue
					known = true
					for (const name of vars) names.add(name)
				}
				if (known) return [...names]
			}
			return []
		},
	}
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/

const propertyKey = (name: string): string => (IDENTIFIER.test(name) ? name : JSON.stringify(name))

const literal = (value: string): string => JSON.stringify(value)

const comment = (text: string): string => text.replace(/\*\//g, "*\\/").replace(/[\r\n]+/g, " ")

const union = (values: readonly string[], empty = "never"): string =>
	values.length === 0 ? empty : values.map(literal).join(" | ")

function pascalCase(value: string): string {
	const words = value.split(/[^A-Za-z0-9]+/).filter((w) => w !== "")
	const joined = words.map((w) => (w[0] as string).toUpperCase() + w.slice(1)).join("")
	if (joined === "") return "Job"
	return /^[0-9]/.test(joined) ? `Job${joined}` : joined
}

/** Assign every job type a distinct TypeScript name stem, in sorted job type order. */
function jobTypeNames(types: readonly string[]): Map<string, string> {
	const taken = new Set<string>()
	const out = new Map<string, string>()
	for (const type of types) {
		const base = pascalCase(type)
		let name = base
		for (let n = 2; taken.has(name); n++) name = `${base}${n}`
		taken.add(name)
		out.set(type, name)
	}
	return out
}

function refList(refs: readonly ContractElementRef[]): string {
	return refs.map((r) => `${r.processId}#${r.elementId}`).join(", ")
}

function renderKeys(name: string, keys: readonly ContractVariable[], doc: string): string[] {
	const lines = [`/** ${comment(doc)} */`, `export interface ${name} {`]
	for (const key of keys) {
		lines.push(`\t${propertyKey(key.name)}${key.required ? "" : "?"}: unknown`)
	}
	lines.push("}")
	return lines
}

function renderConstUnion(
	constName: string,
	typeName: string,
	values: readonly string[],
): string[] {
	return [
		`export const ${constName} = [${values.map(literal).join(", ")}] as const`,
		`export type ${typeName} = (typeof ${constName})[number]`,
	]
}

/**
 * Render the {@link ProcessContract} of one or more BPMN definitions as
 * TypeScript source. The output is deterministic (everything sorted) and
 * starts with a "do not edit" header.
 *
 * @example
 * ```ts
 * import { Bpmn, generateProcessTypes } from "@bpmnkit/core"
 * const source = generateProcessTypes(Bpmn.parse(xml))
 * ```
 */
export function generateProcessTypes(
	definitions: BpmnDefinitions | readonly BpmnDefinitions[],
	options: ProcessTypesOptions = {},
): string {
	const contract = extractProcessContract(definitions)
	const banner = options.banner ?? "generated by casen gen types — do not edit"
	const names = jobTypeNames(contract.jobs.map((j) => j.type))
	const out: string[] = [
		`// ${comment(banner)}`,
		"//",
		"// Keys are exact; values are `unknown` because FEEL cannot be typed statically.",
		"// Optional keys are ones the model does not guarantee. See the typed workers guide:",
		"// https://bpmnkit.com/docs/guides/typed-workers",
	]
	if (contract.dynamicJobTypes.length > 0) {
		out.push(
			`// Skipped dynamic job types (FEEL expressions): ${comment(refList(contract.dynamicJobTypes))}`,
		)
	}
	out.push("")

	out.push(...renderConstUnion("processIds", "ProcessId", contract.processIds), "")
	out.push(
		...renderConstUnion(
			"jobTypes",
			"JobType",
			contract.jobs.map((j) => j.type),
		),
		"",
	)

	for (const job of contract.jobs) {
		const stem = names.get(job.type) as string
		const where = `Job type ${literal(job.type)} — ${refList(job.elements)}`
		out.push(...renderKeys(`${stem}Variables`, job.variables, `Variables of ${where}`), "")
		out.push(...renderKeys(`${stem}Output`, job.output, `Output of ${where}`), "")
		out.push(`/** Task headers of ${comment(where)} */`, `export interface ${stem}Headers {`)
		for (const header of job.headers) {
			out.push(
				`\treadonly ${propertyKey(header.key)}${header.required ? "" : "?"}: ${union(header.values)}`,
			)
		}
		out.push("}", "")
	}

	out.push(
		"/** Job type → the contract a worker for it can rely on. */",
		"export type JobTypes = {",
	)
	for (const job of contract.jobs) {
		const stem = names.get(job.type) as string
		const processes = [...new Set(job.elements.map((e) => e.processId))]
		const errorsType = job.errors === "any" ? "string" : union(job.errors)
		out.push(
			`\t${literal(job.type)}: {`,
			`\t\tvariables: ${stem}Variables`,
			`\t\toutput: ${stem}Output`,
			`\t\theaders: ${stem}Headers`,
			`\t\terrors: ${errorsType}`,
			`\t\tprocessIds: ${union(processes)}`,
			`\t\telementIds: ${union(job.elements.map((e) => e.elementId))}`,
			"\t}",
		)
	}
	out.push("}", "")

	out.push("/** Message name → the correlation key expressions its subscriptions use. */")
	out.push("export interface Messages {")
	for (const message of contract.messages) {
		const keys = message.correlationKeys
		out.push(
			`\t/** ${comment(
				keys.length > 0
					? `Correlation key: ${keys.join(" | ")} — ${refList(message.elements)}`
					: `No correlation key — ${refList(message.elements)}`,
			)} */`,
			`\t${propertyKey(message.name)}: { correlationKey: ${union(keys, "undefined")} }`,
		)
	}
	out.push("}")
	out.push(
		...renderConstUnion(
			"messageNames",
			"MessageName",
			contract.messages.map((m) => m.name),
		),
		"",
	)

	const codeSection = (
		constName: string,
		typeName: string,
		doc: string,
		list: CodeContract[],
	): void => {
		out.push("/**", ` * ${doc}`)
		for (const item of list) out.push(` * - ${comment(`${item.code} — ${refList(item.elements)}`)}`)
		out.push(
			" */",
			...renderConstUnion(
				constName,
				typeName,
				list.map((c) => c.code),
			),
			"",
		)
	}
	codeSection("signalNames", "SignalName", "Signal names thrown or caught.", contract.signals)
	codeSection("errorCodes", "ErrorCode", "Error codes thrown or caught.", contract.errors)
	codeSection(
		"escalationCodes",
		"EscalationCode",
		"Escalation codes thrown or caught.",
		contract.escalations,
	)

	// An empty body renders as `{}` rather than a brace pair split over two lines.
	return `${out
		.join("\n")
		.replace(/\{\n\}/g, "{}")
		.trimEnd()}\n`
}
