/**
 * Scenario runner backed by the WasmEngine (reebe-wasm).
 *
 * Works in both browser and Node.js:
 *   - Browser: WASM is loaded via the default export (fetch-based).
 *   - Node.js:  WASM bytes are read from disk via initSync to avoid
 *               Node's lack of fetch() support for file:// URLs.
 *
 * Creates a fresh WasmEngine per scenario for clean isolation, deploys the
 * current BPMN XML (and all referenced DMN/BPMN resources recursively), drives
 * jobs and native user tasks to completion using mock outputs from the scenario
 * definition, delivers the message each waiting receive task expects, then
 * asserts expectations.
 */

// ── Snapshot types (mirrors wasm-adapter shape) ───────────────────────────────

interface WasmProcessInstance {
	key: number
	bpmn_process_id: string
	state: string
}

interface WasmJob {
	key: number
	job_type: string
	state: string
	process_instance_key: number
	element_id: string
}

interface WasmElementInstance {
	key: number
	process_instance_key: number
	element_id: string
	element_type: string
	state: string
}

interface WasmUserTask {
	key: number
	process_instance_key: number
	element_id: string
	state: string
}

interface WasmMessageSubscription {
	key: number
	message_name: string
	correlation_key: string
	element_instance_key: number
	state: string
}

interface WasmVariable {
	name: string
	value: unknown
	process_instance_key: number
}

interface WasmIncident {
	process_instance_key: number
	element_id: string
	error_type: string
	error_message: string | null
}

interface EventLogRecord {
	record_type: string
	value_type: string
	intent: string
	payload: Record<string, unknown>
}

interface WasmSnapshot {
	processInstances: WasmProcessInstance[]
	elementInstances: WasmElementInstance[]
	jobs: WasmJob[]
	variables: WasmVariable[]
	incidents: WasmIncident[]
	eventLog: EventLogRecord[]
	userTasks: WasmUserTask[]
	messageSubscriptions: WasmMessageSubscription[]
}

interface DeployResponse {
	deployments: Array<{ bpmnProcessId: string }>
}

interface WasmEngineInstance {
	deploy(xml: string): unknown
	create_process_instance(processId: string, variables: string): void
	activate_job(key: number, worker: string, timeout: number): void
	complete_job(key: number, variables: string): void
	complete_user_task(key: number, variables: string): void
	fail_job(key: number, retries: number, message: string): void
	publish_message(name: string, correlationKey: string, variables: string): void
	snapshot(): unknown
	free(): void
}

// ── Scenario types ────────────────────────────────────────────────────────────

export interface ScenarioLike {
	id: string
	name: string
	processId?: string
	inputs?: Record<string, unknown>
	mocks?: Record<string, { outputs?: Record<string, unknown>; error?: string }>
	expect?: {
		path?: string[]
		variables?: Record<string, unknown>
	}
}

export interface ScenarioResultLike {
	scenarioId: string
	scenarioName: string
	passed: boolean
	visitedElements: string[]
	finalVariables: Record<string, unknown>
	feelEvals: Array<{ elementId: string; property: string; expression: string; result: unknown }>
	errors: Array<{ elementId?: string; message: string }>
	failures: Array<{ field: string; expected: unknown; actual: unknown }>
	durationMs: number
}

// ── WASM initialisation ───────────────────────────────────────────────────────

let wasmReady = false

async function ensureWasmInit(): Promise<void> {
	if (wasmReady) return
	let mod: typeof import("@bpmnkit/reebe-wasm")
	try {
		mod = await import("@bpmnkit/reebe-wasm")
	} catch (e) {
		throw new Error(
			`@bpmnkit/reebe-wasm is not installed. Run: npm install @bpmnkit/reebe-wasm\nCaused by: ${e instanceof Error ? e.message : String(e)}`,
		)
	}
	// Node.js: fetch() does not support file:// URLs generated by wasm-bindgen,
	// so we read the .wasm bytes from disk and use initSync.
	if (typeof process !== "undefined" && typeof process.versions?.node === "string") {
		const { readFileSync } = await import("node:fs")
		const { createRequire } = await import("node:module")
		const { dirname, resolve } = await import("node:path")
		const req = createRequire(import.meta.url)
		const jsPath: string = req.resolve("@bpmnkit/reebe-wasm")
		const wasmPath = resolve(dirname(jsPath), "reebe_wasm_bg.wasm")
		mod.initSync({ module: readFileSync(wasmPath) })
	} else {
		await mod.default()
	}
	wasmReady = true
}

// ── Recursive dependency deployment ──────────────────────────────────────────

function deployDependencies(
	xml: string,
	engine: WasmEngineInstance,
	getDecisionDmn: ((id: string) => string | null) | undefined,
	getProcessBpmn: ((id: string) => string | null) | undefined,
	deployed: Set<string>,
): string[] {
	const missingDecisions: string[] = []

	// DMN decisions referenced via decisionId="..."
	if (getDecisionDmn) {
		for (const [, id] of xml.matchAll(/decisionId="([^"]+)"/g)) {
			if (!id || deployed.has(`dmn:${id}`)) continue
			deployed.add(`dmn:${id}`)
			const dmnXml = getDecisionDmn(id)
			if (dmnXml) {
				try {
					engine.deploy(dmnXml)
				} catch {
					missingDecisions.push(id)
				}
			} else {
				missingDecisions.push(id)
			}
		}
	}

	// Sub-processes / call activities referenced via calledElement="..."
	if (getProcessBpmn) {
		for (const [, id] of xml.matchAll(/calledElement="([^"]+)"/g)) {
			if (!id || deployed.has(`bpmn:${id}`)) continue
			deployed.add(`bpmn:${id}`)
			const bpmnXml = getProcessBpmn(id)
			if (bpmnXml) {
				const nested = deployDependencies(bpmnXml, engine, getDecisionDmn, getProcessBpmn, deployed)
				missingDecisions.push(...nested)
				engine.deploy(bpmnXml)
			}
		}
	}

	return missingDecisions
}

// ── BPMN helpers ─────────────────────────────────────────────────────────────

/**
 * Extract condition expressions keyed by sequence flow ID from BPMN XML.
 * Used to reconstruct FEEL evaluations from SEQUENCE_FLOW_TAKEN event log records.
 */
function extractFlowConditions(bpmnXml: string): Map<string, string> {
	const result = new Map<string, string>()
	// Strategy: find each conditionExpression element, then look backward to the
	// nearest enclosing <sequenceFlow id="..."> opening tag.  Using a greedy
	// prefix ([\s\S]*) forces the match to the LAST occurrence before the
	// conditionExpression, which is always the immediately enclosing flow.
	// This avoids the self-closing `/>` confusion that plagues forward-matching regexes.
	const condPattern =
		/<(?:[a-zA-Z]+:)?conditionExpression[^>]*>([\s\S]*?)<\/(?:[a-zA-Z]+:)?conditionExpression>/g
	for (const condMatch of bpmnXml.matchAll(condPattern)) {
		const rawExpr = condMatch[1]?.trim() ?? ""
		const condition =
			rawExpr.startsWith("<![CDATA[") && rawExpr.endsWith("]]>") ? rawExpr.slice(9, -3) : rawExpr
		// Slice everything before this conditionExpression and find the last sequenceFlow id
		const before = bpmnXml.slice(0, condMatch.index)
		const flowMatch = before.match(/[\s\S]*<(?:[a-zA-Z]+:)?sequenceFlow\b[^>]*\bid="([^"]+)"/)
		if (flowMatch?.[1]) {
			result.set(flowMatch[1], condition)
		}
	}
	return result
}

/**
 * Ensure BRT result variables are propagated to the parent process scope.
 *
 * When a BPMN `businessRuleTask` has both `zeebe:calledDecision resultVariable="X"`
 * and a `zeebe:ioMapping` element, the WASM engine only propagates explicitly mapped
 * output variables.  Without an output entry for X, the result stays in the element
 * scope (scope_key = element instance key) and is cleaned up when the BRT completes —
 * never reaching the process instance scope where the runner's snapshot reads variables.
 *
 * This function rewrites the XML so that each such BRT has an explicit
 * `<zeebe:output source="=X" target="X"/>` entry, mirroring real Zeebe behaviour
 * where resultVariable is always stored at the parent scope.
 */
function ensureBrtResultVariableOutputs(xml: string): string {
	const brtPattern =
		/(<(?:[a-zA-Z]+:)?businessRuleTask\b[^>]*>)([\s\S]*?)(<\/(?:[a-zA-Z]+:)?businessRuleTask>)/g
	return xml.replace(brtPattern, (_match, open: string, body: string, close: string) => {
		const rvMatch = /resultVariable="([^"]+)"/.exec(body)
		if (!rvMatch?.[1]) return open + body + close // no calledDecision resultVariable
		const resultVar = rvMatch[1]

		// Already has an output entry for this variable? Nothing to do
		if (new RegExp(`<(?:[a-zA-Z]+:)?output\\b[^>]*target="${resultVar}"`).test(body))
			return open + body + close

		const outputEntry = `<zeebe:output source="=${resultVar}" target="${resultVar}"/>`
		const hasIoMapping = /<(?:[a-zA-Z]+:)?ioMapping\b/.test(body)

		let patched: string
		if (!hasIoMapping) {
			// No ioMapping at all — inject one before the closing extensionElements tag
			patched = body.replace(
				/(<\/(?:[a-zA-Z]+:)?extensionElements>)/,
				`<zeebe:ioMapping>${outputEntry}</zeebe:ioMapping>$1`,
			)
		} else if (/<(?:[a-zA-Z]+:)?ioMapping\s*\/>/.test(body)) {
			// Self-closing <zeebe:ioMapping/> — expand and inject
			patched = body.replace(
				/<(?:[a-zA-Z]+:)?ioMapping\s*\/>/,
				`<zeebe:ioMapping>${outputEntry}</zeebe:ioMapping>`,
			)
		} else {
			// Open/close <zeebe:ioMapping>…</zeebe:ioMapping> — inject before closing tag
			patched = body.replace(/(<\/(?:[a-zA-Z]+:)?ioMapping>)/, `${outputEntry}$1`)
		}

		return open + patched + close
	})
}

// ── BRT result variable post-hoc evaluation ──────────────────────────────────

interface BrtInfo {
	elementId: string
	decisionId: string
	resultVar: string
}

function extractBrtInfos(bpmnXml: string): BrtInfo[] {
	const infos: BrtInfo[] = []
	const pattern =
		/<(?:[a-zA-Z]+:)?businessRuleTask\b([^>]*)>([\s\S]*?)<\/(?:[a-zA-Z]+:)?businessRuleTask>/g
	for (const m of bpmnXml.matchAll(pattern)) {
		const attrs = m[1] ?? ""
		const body = m[2] ?? ""
		const idMatch = /\bid="([^"]+)"/.exec(attrs)
		const decisionIdMatch = /decisionId="([^"]+)"/.exec(body)
		const resultVarMatch = /resultVariable="([^"]+)"/.exec(body)
		if (idMatch?.[1] && decisionIdMatch?.[1] && resultVarMatch?.[1]) {
			infos.push({
				elementId: idMatch[1],
				decisionId: decisionIdMatch[1],
				resultVar: resultVarMatch[1],
			})
		}
	}
	return infos
}

interface DmnDecisionTable {
	hitPolicy: string
	inputs: string[] // FEEL expressions for input columns
	outputs: string[] // variable names for output columns
	rules: Array<{
		inputEntries: string[] // unary test expressions (empty = match any)
		outputEntries: string[] // FEEL value expressions
	}>
}

function parseDmnDecisionTable(dmnXml: string, decisionId: string): DmnDecisionTable | null {
	const decisionMatch = new RegExp(
		`<(?:[a-zA-Z]+:)?decision\\b[^>]*\\bid="${decisionId}"[^>]*>[\\s\\S]*?<\\/(?:[a-zA-Z]+:)?decision>`,
	).exec(dmnXml)
	if (!decisionMatch) return null
	const decisionBody = decisionMatch[0]

	const tableMatch =
		/<(?:[a-zA-Z]+:)?decisionTable\b([^>]*)>([\s\S]*?)<\/(?:[a-zA-Z]+:)?decisionTable>/.exec(
			decisionBody,
		)
	if (!tableMatch) return null
	const hitPolicy = /hitPolicy="([^"]*)"/.exec(tableMatch[1] ?? "")?.[1] ?? "UNIQUE"
	const tableBody = tableMatch[2] ?? ""

	const extractText = (xml: string) =>
		/<(?:[a-zA-Z]+:)?text\b[^>]*>([\s\S]*?)<\/(?:[a-zA-Z]+:)?text>/.exec(xml)?.[1]?.trim() ?? ""

	const inputs: string[] = []
	for (const m of tableBody.matchAll(
		/<(?:[a-zA-Z]+:)?input\b[^>]*>([\s\S]*?)<\/(?:[a-zA-Z]+:)?input>/g,
	)) {
		const exprBody =
			/<(?:[a-zA-Z]+:)?inputExpression\b[^>]*>([\s\S]*?)<\/(?:[a-zA-Z]+:)?inputExpression>/.exec(
				m[1] ?? "",
			)?.[1] ?? ""
		inputs.push(extractText(exprBody))
	}

	const outputs: string[] = []
	for (const m of tableBody.matchAll(
		/<(?:[a-zA-Z]+:)?output\b([^/>]*?)(?:\/>|>[\s\S]*?<\/(?:[a-zA-Z]+:)?output>)/g,
	)) {
		outputs.push(/\bname="([^"]*)"/.exec(m[1] ?? "")?.[1] ?? "")
	}

	const rules: DmnDecisionTable["rules"] = []
	for (const ruleMatch of tableBody.matchAll(
		/<(?:[a-zA-Z]+:)?rule\b[^>]*>([\s\S]*?)<\/(?:[a-zA-Z]+:)?rule>/g,
	)) {
		const ruleBody = ruleMatch[1] ?? ""
		const inputEntries: string[] = []
		for (const ie of ruleBody.matchAll(
			/<(?:[a-zA-Z]+:)?inputEntry\b[^>]*>([\s\S]*?)<\/(?:[a-zA-Z]+:)?inputEntry>/g,
		))
			inputEntries.push(extractText(ie[1] ?? ""))
		const outputEntries: string[] = []
		for (const oe of ruleBody.matchAll(
			/<(?:[a-zA-Z]+:)?outputEntry\b[^>]*>([\s\S]*?)<\/(?:[a-zA-Z]+:)?outputEntry>/g,
		))
			outputEntries.push(extractText(oe[1] ?? ""))
		rules.push({ inputEntries, outputEntries })
	}

	return { hitPolicy, inputs, outputs, rules }
}

function evalDmnDecisionTable(table: DmnDecisionTable, vars: Record<string, unknown>): unknown {
	const feel = feelModule
	if (!feel) return null
	const ctx = { vars: vars as Record<string, import("@bpmnkit/feel").FeelValue> }

	const collectResults: unknown[] = []
	for (const rule of table.rules) {
		let matches = true
		for (let i = 0; i < table.inputs.length; i++) {
			const inputExpr = table.inputs[i] ?? ""
			const testExpr = rule.inputEntries[i] ?? ""
			if (!testExpr) continue // empty = any

			const inputParsed = feel.parseExpression(inputExpr)
			if (!inputParsed.ast) {
				matches = false
				break
			}
			const inputVal = feel.evaluate(inputParsed.ast, ctx)

			const testParsed = feel.parseUnaryTests(testExpr)
			if (!testParsed.ast) {
				matches = false
				break
			}
			if (!feel.evaluateUnaryTests(testParsed.ast, inputVal, ctx)) {
				matches = false
				break
			}
		}
		if (!matches) continue

		if (table.outputs.length === 1) {
			const expr = rule.outputEntries[0] ?? ""
			if (expr) {
				const parsed = feel.parseExpression(expr)
				if (parsed.ast) collectResults.push(feel.evaluate(parsed.ast, ctx))
			}
		} else {
			const row: Record<string, unknown> = {}
			for (let i = 0; i < table.outputs.length; i++) {
				const name = table.outputs[i]
				const expr = rule.outputEntries[i] ?? ""
				if (name && expr) {
					const parsed = feel.parseExpression(expr)
					if (parsed.ast) row[name] = feel.evaluate(parsed.ast, ctx)
				}
			}
			collectResults.push(row)
		}
	}

	// Apply hit policy
	if (table.hitPolicy === "FIRST") return collectResults[0] ?? null
	if (table.hitPolicy === "UNIQUE" || table.hitPolicy === "ANY") return collectResults[0] ?? null
	return collectResults // COLLECT, RULE ORDER, etc.
}

// Lazily cached feel module reference (avoids repeated dynamic imports)
let feelModule: typeof import("@bpmnkit/feel") | null = null

async function ensureFeelModule(): Promise<void> {
	if (feelModule) return
	feelModule = await import("@bpmnkit/feel")
}

/**
 * For visited BRTs that have a resultVariable, evaluate the DMN decision table
 * directly using the FEEL engine and return {resultVar: value} pairs.
 *
 * The WASM browser engine cleans up BRT local-scope variables on element
 * completion and does not propagate the resultVariable to the process scope
 * snapshot.  Evaluating the DMN with the FEEL engine directly sidesteps this
 * limitation.
 */
async function evaluateBrtResultVariables(
	bpmnXml: string,
	visitedElementIds: string[],
	vars: Record<string, unknown>,
	getDecisionDmn: ((id: string) => string | null) | undefined,
): Promise<Record<string, unknown>> {
	if (!getDecisionDmn) return {}

	const allBrts = extractBrtInfos(bpmnXml)
	const visitedBrts = allBrts.filter((b) => visitedElementIds.includes(b.elementId))
	if (visitedBrts.length === 0) return {}

	await ensureFeelModule()
	const result: Record<string, unknown> = {}

	for (const { decisionId, resultVar } of visitedBrts) {
		const dmnXml = getDecisionDmn(decisionId)
		if (!dmnXml) continue

		const table = parseDmnDecisionTable(dmnXml, decisionId)
		if (!table) continue

		result[resultVar] = evalDmnDecisionTable(table, vars)
	}

	return result
}

// ── Runner ────────────────────────────────────────────────────────────────────

const MAX_ROUNDS = 200
const TIMEOUT_MS = 10_000

export async function runScenarioWasm(
	xml: string,
	scenario: ScenarioLike,
	getDecisionDmn?: (decisionId: string) => string | null,
	getProcessBpmn?: (processId: string) => string | null,
): Promise<ScenarioResultLike> {
	const startMs = Date.now()

	await ensureWasmInit()
	const mod = await import("@bpmnkit/reebe-wasm")
	const engine = new mod.WasmEngine() as WasmEngineInstance

	try {
		const deployed = new Set<string>()
		const missingDecisions = deployDependencies(
			xml,
			engine,
			getDecisionDmn,
			getProcessBpmn,
			deployed,
		)
		// Deploy main BPMN (with BRT result variable output mappings patched in)
		const deployResult = engine.deploy(ensureBrtResultVariableOutputs(xml)) as DeployResponse
		const processId = scenario.processId ?? deployResult.deployments[0]?.bpmnProcessId
		if (!processId) {
			return fail(scenario, startMs, "No process found in deployed BPMN.")
		}

		// Start instance
		engine.create_process_instance(processId, JSON.stringify(scenario.inputs ?? {}))

		// Drive the instance: complete jobs and native user tasks with their mocks,
		// and deliver the message each waiting receive task expects.
		const errors: ScenarioResultLike["errors"] = []
		const failedUserTasks = new Set<number>()
		for (let round = 0; round < MAX_ROUNDS; round++) {
			if (Date.now() - startMs > TIMEOUT_MS) break

			const snap = engine.snapshot() as WasmSnapshot
			const pi = snap.processInstances.find((p) => p.bpmn_process_id === processId)

			if (!pi || pi.state !== "ACTIVE") break

			const activatable = snap.jobs.filter(
				(j) => j.state === "ACTIVATABLE" && j.process_instance_key === pi.key,
			)
			// A native user task is not a job; scenarios mock it under the job type
			// `userTask`, as the TypeScript engine runs it.
			const userTasks = snap.userTasks.filter(
				(t) =>
					t.state === "CREATED" && t.process_instance_key === pi.key && !failedUserTasks.has(t.key),
			)
			const receiveTasks = waitingReceiveTasks(snap, pi.key)
			if (activatable.length === 0 && userTasks.length === 0 && receiveTasks.length === 0) break

			for (const job of activatable) {
				try {
					engine.activate_job(job.key, "test-worker", 30_000)
					const mock = scenario.mocks?.[job.job_type]
					if (mock?.error !== undefined) {
						engine.fail_job(job.key, 0, mock.error)
					} else {
						engine.complete_job(job.key, JSON.stringify(mock?.outputs ?? {}))
					}
				} catch {
					// Job may have already been handled — skip
				}
			}

			const userTaskMock = scenario.mocks?.userTask
			for (const task of userTasks) {
				if (userTaskMock?.error !== undefined) {
					// A user task cannot fail on Zeebe; report the mocked failure and leave it open.
					failedUserTasks.add(task.key)
					errors.push({ elementId: task.element_id, message: userTaskMock.error })
					continue
				}
				try {
					engine.complete_user_task(task.key, JSON.stringify(userTaskMock?.outputs ?? {}))
				} catch {
					// Task may have been terminated by an earlier completion this round — skip
				}
			}

			// The TypeScript engine passes a receive task without waiting, and scenarios
			// give the message's variables as start inputs. Publishing the awaited message
			// (with the subscription's own correlation key) keeps the two runners alike.
			for (const sub of receiveTasks) {
				try {
					engine.publish_message(sub.message_name, sub.correlation_key, "{}")
				} catch {
					// Already correlated this round — skip
				}
			}
		}

		// Collect final state
		const snap = engine.snapshot() as WasmSnapshot
		const pi = snap.processInstances.find((p) => p.bpmn_process_id === processId)

		if (!pi) return fail(scenario, startMs, "Process instance not found after run.")

		const timedOut = pi.state === "ACTIVE" && Date.now() - startMs >= TIMEOUT_MS

		const visitedElements = snap.elementInstances
			.filter((e) => e.process_instance_key === pi.key)
			.map((e) => e.element_id)
		// Collect variables: merge snapshot state (deduplicated, final values) with
		// VARIABLE.CREATED events from the event log (catches DMN-produced variables
		// that may not survive snapshot filtering due to scope key differences).
		const piKeyStr = String(pi.key)
		const finalVariables: Record<string, unknown> = {}
		for (const rec of snap.eventLog) {
			if (
				rec.record_type === "EVENT" &&
				rec.value_type === "VARIABLE" &&
				rec.intent === "CREATED" &&
				String(rec.payload.processInstanceKey) === piKeyStr
			) {
				const name = rec.payload.name as string | undefined
				if (name !== undefined) finalVariables[name] = rec.payload.value
			}
		}
		// Snapshot variables override (they represent the final upserted state)
		for (const v of snap.variables.filter((v) => v.process_instance_key === pi.key)) {
			finalVariables[v.name] = v.value
		}

		// BRT resultVariable post-hoc evaluation: the WASM browser engine cleans up
		// BRT local-scope variables on element completion so they never reach the
		// process-scope snapshot.  Evaluate each visited BRT's DMN directly with
		// the FEEL engine and inject the result (snapshot value wins if present).
		const brtResultVars = await evaluateBrtResultVariables(
			xml,
			visitedElements,
			finalVariables,
			getDecisionDmn,
		)
		for (const [k, v] of Object.entries(brtResultVars)) {
			if (!(k in finalVariables)) finalVariables[k] = v
		}

		// Reconstruct FEEL evaluations from SEQUENCE_FLOW_TAKEN events.
		// The WASM engine evaluates conditions but doesn't emit dedicated FEEL records;
		// we pair each taken flow with its conditionExpression from the BPMN XML.
		const flowConditions = extractFlowConditions(xml)
		const feelEvals: ScenarioResultLike["feelEvals"] = []
		for (const rec of snap.eventLog) {
			if (
				rec.record_type === "EVENT" &&
				rec.value_type === "PROCESS_INSTANCE" &&
				rec.intent === "SEQUENCE_FLOW_TAKEN" &&
				String(rec.payload.processInstanceKey) === piKeyStr
			) {
				const flowId = rec.payload.elementId as string | undefined
				const sourceId = rec.payload.sourceElementId as string | undefined
				if (!flowId) continue
				const expression = flowConditions.get(flowId)
				if (expression !== undefined) {
					feelEvals.push({
						elementId: sourceId ?? flowId,
						property: "condition",
						expression,
						result: true,
					})
				}
			}
		}

		for (const i of snap.incidents.filter((i) => i.process_instance_key === pi.key)) {
			errors.push({ elementId: i.element_id, message: i.error_message ?? i.error_type })
		}

		for (const id of missingDecisions) {
			errors.push({ message: `DMN decision '${id}' not found. Create the DMN in the Models view.` })
		}

		if (timedOut) {
			errors.push({ message: `Scenario timed out after ${TIMEOUT_MS}ms` })
		}

		// Evaluate assertions
		const failures: ScenarioResultLike["failures"] = []

		if (scenario.expect?.path !== undefined) {
			let cursor = 0
			for (const expectedId of scenario.expect.path) {
				const idx = visitedElements.indexOf(expectedId, cursor)
				if (idx === -1) {
					failures.push({
						field: "path",
						expected: expectedId,
						actual: `not found in [${visitedElements.join(", ")}]`,
					})
				} else {
					cursor = idx + 1
				}
			}
		}

		if (scenario.expect?.variables !== undefined) {
			for (const [key, expectedValue] of Object.entries(scenario.expect.variables)) {
				const actualValue = finalVariables[key]
				if (!deepEqual(actualValue, expectedValue)) {
					failures.push({ field: `variables.${key}`, expected: expectedValue, actual: actualValue })
				}
			}
		}

		return {
			scenarioId: scenario.id,
			scenarioName: scenario.name,
			passed: errors.length === 0 && failures.length === 0,
			visitedElements,
			finalVariables,
			feelEvals,
			errors,
			failures,
			durationMs: Date.now() - startMs,
		}
	} finally {
		engine.free()
	}
}

/** Message subscriptions of receive tasks that are waiting in this instance. */
function waitingReceiveTasks(
	snap: WasmSnapshot,
	processInstanceKey: number,
): WasmMessageSubscription[] {
	const waiting = new Set(
		snap.elementInstances
			.filter(
				(e) =>
					e.process_instance_key === processInstanceKey &&
					e.element_type === "RECEIVE_TASK" &&
					e.state === "ACTIVATED",
			)
			.map((e) => e.key),
	)
	return snap.messageSubscriptions.filter(
		(s) => s.state === "OPENED" && waiting.has(s.element_instance_key),
	)
}

/** Structural equality of JSON values; object key order does not matter. */
function deepEqual(a: unknown, b: unknown): boolean {
	if (a === b) return true
	if (typeof a !== "object" || typeof b !== "object" || a === null || b === null) return false
	if (Array.isArray(a) !== Array.isArray(b)) return false
	if (Array.isArray(a) && Array.isArray(b)) {
		return a.length === b.length && a.every((item, i) => deepEqual(item, b[i]))
	}
	const aRecord = a as Record<string, unknown>
	const bRecord = b as Record<string, unknown>
	const aKeys = Object.keys(aRecord)
	return (
		aKeys.length === Object.keys(bRecord).length &&
		aKeys.every((k) => Object.hasOwn(bRecord, k) && deepEqual(aRecord[k], bRecord[k]))
	)
}

function fail(scenario: ScenarioLike, startMs: number, message: string): ScenarioResultLike {
	return {
		scenarioId: scenario.id,
		scenarioName: scenario.name,
		passed: false,
		visitedElements: [],
		finalVariables: {},
		feelEvals: [],
		errors: [{ message }],
		failures: [{ field: "start", expected: "process to deploy and start", actual: message }],
		durationMs: Date.now() - startMs,
	}
}
