/**
 * Writes `src/bpmn/zeebe-placement.ts` from the vendored descriptors.
 *
 *   pnpm --filter @bpmnkit/core generate:placement
 *   pnpm --filter @bpmnkit/core check:placement
 *
 * The resolution itself lives in `zeebe-placement-table.ts`, which the test
 * checking the table for staleness imports directly — the two must agree, and
 * calling the same function is the only way to be sure they do.
 */
import { writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { computePlacementTable } from "./zeebe-placement-table.js"

const OUTPUT = join(
	dirname(fileURLToPath(import.meta.url)),
	"..",
	"src",
	"bpmn",
	"zeebe-placement.ts",
)

const rows = computePlacementTable()

const source = `// Generated by scripts/generate-zeebe-placement.ts — do not edit.
// Source: descriptors/zeebe.json (zeebe-bpmn-moddle, MIT) resolved against
// descriptors/bpmn.json (bpmn-moddle, MIT). Regenerate with:
//   pnpm --filter @bpmnkit/core generate:placement

/**
 * Where each Zeebe extension element may be placed, keyed by element name.
 *
 * The value is the set of element names that may own it. Owners are BPMN
 * elements for extensions that sit in an \`extensionElements\` bag, and Zeebe
 * elements for the few that nest inside another extension.
 *
 * An extension absent from this table is one the descriptor says nothing about;
 * see \`isZeebePlacementAllowed\` for what that means.
 */
export const ZEEBE_PLACEMENT: Readonly<Record<string, readonly string[]>> = {
${rows.map(([tag, owners]) => `\t"${tag}": [${owners.map((owner) => `"${owner}"`).join(", ")}],`).join("\n")}
} as const
`

if (process.argv.includes("--check")) {
	// Compare the table, not the file. Biome owns the formatting of the generated
	// source, so a byte comparison would report the table stale every time Biome
	// wrapped a line differently — and a check that cries wolf gets disabled.
	const { ZEEBE_PLACEMENT } = (await import("../src/bpmn/zeebe-placement.js")) as {
		ZEEBE_PLACEMENT: Record<string, readonly string[]>
	}
	const expected = JSON.stringify(Object.fromEntries(rows))
	const actual = JSON.stringify(
		Object.fromEntries(
			Object.entries(ZEEBE_PLACEMENT).sort(([left], [right]) => left.localeCompare(right)),
		),
	)
	if (expected !== actual) {
		console.error(
			[
				"src/bpmn/zeebe-placement.ts no longer matches the descriptors.",
				"Run: pnpm --filter @bpmnkit/core generate:placement",
			].join("\n"),
		)
		process.exit(1)
	}
	console.log(`zeebe-placement.ts is up to date (${rows.length} extensions).`)
} else {
	writeFileSync(OUTPUT, source)
	console.log(`Wrote ${OUTPUT} (${rows.length} extensions). Run biome to format it.`)
}
