export interface CatalogEntry {
	id: string
	name: string
	description: string
	url: string
	/** Suggested id prefix for generated templates */
	idPrefix: string
	/** Default auth hint */
	defaultAuth: "noAuth" | "apiKey" | "basic" | "bearer" | "oauth-client-credentials-flow"
}

export const CATALOG: CatalogEntry[] = [
	{
		id: "github",
		name: "GitHub REST API",
		description: "Manage repos, issues, PRs, actions, and more via the GitHub REST API",
		url: "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json",
		idPrefix: "io.github",
		defaultAuth: "bearer",
	},
	{
		id: "cloudflare",
		name: "Cloudflare API",
		description: "Manage DNS, zones, Workers, and other Cloudflare resources",
		url: "https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.json",
		idPrefix: "io.cloudflare",
		defaultAuth: "bearer",
	},
	{
		id: "stripe",
		name: "Stripe API",
		description: "Payments, subscriptions, invoices, and more via the Stripe REST API",
		url: "https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json",
		idPrefix: "io.stripe",
		defaultAuth: "basic",
	},
	{
		id: "notion",
		name: "Notion API",
		description: "Read and write Notion pages, databases, and blocks",
		url: "https://raw.githubusercontent.com/notion-sdk-python/notion-sdk-py/main/openapi.yaml",
		idPrefix: "io.notion",
		defaultAuth: "bearer",
	},
	{
		id: "resend",
		name: "Resend Email API",
		description: "Send transactional emails via the Resend API",
		url: "https://raw.githubusercontent.com/resendlabs/resend-openapi/main/resend.yaml",
		idPrefix: "io.resend",
		defaultAuth: "bearer",
	},
	{
		id: "openai",
		name: "OpenAI API",
		description: "Chat completions, embeddings, images, and more from the OpenAI platform",
		url: "https://raw.githubusercontent.com/openai/openai-openapi/master/openapi.yaml",
		idPrefix: "io.openai",
		defaultAuth: "bearer",
	},
	{
		id: "figma",
		name: "Figma API",
		description: "Read and write Figma files, components, comments, and team resources",
		url: "https://raw.githubusercontent.com/figma/rest-api-spec/main/openapi/openapi.yaml",
		idPrefix: "io.figma",
		defaultAuth: "bearer",
	},
	{
		id: "twilio",
		name: "Twilio Messaging API",
		description: "Send and manage SMS, MMS, and WhatsApp messages via Twilio",
		url: "https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_messaging_v1.json",
		idPrefix: "io.twilio",
		defaultAuth: "basic",
	},
	{
		id: "slack",
		name: "Slack Web API",
		description: "Post messages, manage channels, users, and workflows in Slack",
		url: "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/slack.com/1.7.0/openapi.yaml",
		idPrefix: "io.slack",
		defaultAuth: "bearer",
	},
	{
		id: "jira",
		name: "Atlassian Jira API",
		description: "Manage Jira issues, projects, boards, and sprints",
		url: "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/atlassian.com/jira/1001.0.0-SNAPSHOT/openapi.yaml",
		idPrefix: "io.atlassian.jira",
		defaultAuth: "bearer",
	},
	{
		id: "hubspot",
		name: "HubSpot CRM API",
		description: "Manage contacts, companies, deals, and pipelines in the HubSpot CRM platform",
		url: "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/hubapi.com/crm/v3/openapi.yaml",
		idPrefix: "com.hubspot",
		defaultAuth: "oauth-client-credentials-flow",
	},
	{
		id: "discord",
		name: "Discord API",
		description: "Manage Discord bots, messages, channels, guilds, and webhooks",
		url: "https://raw.githubusercontent.com/discord/discord-api-spec/main/specs/openapi.json",
		idPrefix: "com.discord",
		defaultAuth: "bearer",
	},
	{
		id: "pagerduty",
		name: "PagerDuty API",
		description: "Create and manage incidents, escalation policies, and on-call schedules",
		url: "https://raw.githubusercontent.com/PagerDuty/api-schema/main/reference/REST/openapiv3.json",
		idPrefix: "com.pagerduty",
		defaultAuth: "apiKey",
	},
	{
		id: "zoom",
		name: "Zoom API",
		description: "Create and manage Zoom meetings, webinars, recordings, and users",
		url: "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/zoom.us/2.0.0/openapi.yaml",
		idPrefix: "us.zoom",
		defaultAuth: "oauth-client-credentials-flow",
	},
	{
		id: "mailchimp",
		name: "Mailchimp API",
		description: "Manage email campaigns, audiences, automations, and transactional messages",
		url: "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/mailchimp.com/3.0.55/openapi.yaml",
		idPrefix: "com.mailchimp",
		defaultAuth: "apiKey",
	},
	{
		id: "asana",
		name: "Asana API",
		description: "Manage tasks, projects, teams, and workspaces in Asana",
		url: "https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml",
		idPrefix: "com.asana",
		defaultAuth: "bearer",
	},
	{
		id: "sendgrid",
		name: "SendGrid Mail API",
		description: "Send transactional and marketing emails with templates, tracking, and analytics",
		url: "https://raw.githubusercontent.com/twilio/sendgrid-oai/main/spec/json/tsg_mail_v3.json",
		idPrefix: "com.sendgrid",
		defaultAuth: "bearer",
	},
	{
		id: "paypal",
		name: "PayPal Payments API",
		description: "Authorize, capture, and refund online payment transactions via PayPal",
		url: "https://raw.githubusercontent.com/paypal/paypal-rest-api-specifications/main/openapi/payments_payment_v2.json",
		idPrefix: "com.paypal",
		defaultAuth: "oauth-client-credentials-flow",
	},
	{
		id: "plaid",
		name: "Plaid API",
		description: "Link bank accounts, read transactions, and verify identity via Plaid",
		url: "https://raw.githubusercontent.com/plaid/plaid-openapi/master/2020-09-14.yml",
		idPrefix: "com.plaid",
		defaultAuth: "apiKey",
	},
	{
		id: "vercel",
		name: "Vercel API",
		description: "Manage Vercel deployments, projects, domains, and team resources",
		url: "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/vercel.com/0.0.1/openapi.yaml",
		idPrefix: "com.vercel",
		defaultAuth: "bearer",
	},
	{
		id: "anthropic",
		name: "Anthropic API",
		description:
			"Access Claude models for text generation, vision, and tool use via the Anthropic API",
		url: "https://raw.githubusercontent.com/anthropics/anthropic-openapi/main/openapi.yaml",
		idPrefix: "com.anthropic",
		defaultAuth: "apiKey",
	},
	{
		id: "shopify",
		name: "Shopify Admin API",
		description: "Manage Shopify store products, orders, customers, inventory, and fulfillments",
		url: "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/shopify.dev/admin/2023-04/openapi.yaml",
		idPrefix: "dev.shopify",
		defaultAuth: "bearer",
	},
	{
		id: "datadog",
		name: "Datadog API",
		description: "Submit metrics, manage monitors, dashboards, logs, and alerts in Datadog",
		url: "https://raw.githubusercontent.com/DataDog/datadog-api-client-python/master/openapi.yaml",
		idPrefix: "com.datadoghq",
		defaultAuth: "apiKey",
	},
	{
		id: "sentry",
		name: "Sentry API",
		description: "Manage Sentry projects, issues, events, releases, and team members",
		url: "https://raw.githubusercontent.com/getsentry/sentry-api-schema/main/openapi-derefed.json",
		idPrefix: "io.sentry",
		defaultAuth: "bearer",
	},
	{
		id: "intercom",
		name: "Intercom API",
		description: "Manage contacts, conversations, messages, and support workflows in Intercom",
		url: "https://raw.githubusercontent.com/intercom/Intercom-OpenAPI/main/descriptions/2.10/api.intercom.io.yaml",
		idPrefix: "io.intercom",
		defaultAuth: "bearer",
	},
	{
		id: "contentful",
		name: "Contentful Management API",
		description: "Create and manage content types, entries, assets, and spaces in Contentful CMS",
		url: "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/contentful.com/management.2/openapi.yaml",
		idPrefix: "com.contentful",
		defaultAuth: "bearer",
	},
	{
		id: "airtable",
		name: "Airtable API",
		description: "Read and write records, tables, fields, and views in Airtable bases",
		url: "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/airtable.com/0.1.0/openapi.yaml",
		idPrefix: "com.airtable",
		defaultAuth: "bearer",
	},
	{
		id: "twitch",
		name: "Twitch Helix API",
		description:
			"Manage Twitch streams, channels, clips, users, subscriptions, and EventSub webhooks",
		url: "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/twitch.tv/helix/latest/openapi.yaml",
		idPrefix: "tv.twitch",
		defaultAuth: "oauth-client-credentials-flow",
	},
	{
		id: "klaviyo",
		name: "Klaviyo API",
		description: "Manage email/SMS campaigns, lists, profiles, flows, and events in Klaviyo",
		url: "https://raw.githubusercontent.com/klaviyo/klaviyo-api-node/main/openapi/openapi.yaml",
		idPrefix: "com.klaviyo",
		defaultAuth: "apiKey",
	},
	{
		id: "brex",
		name: "Brex API",
		description: "Manage Brex business accounts, cards, transactions, and expense reimbursements",
		url: "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/brex.com/payments/0.1/openapi.yaml",
		idPrefix: "com.brex",
		defaultAuth: "oauth-client-credentials-flow",
	},
	{
		id: "box",
		name: "Box API",
		description:
			"Upload, download, organize, and share files and folders via the Box cloud storage platform",
		url: "https://raw.githubusercontent.com/box/box-openapi/main/openapi.json",
		idPrefix: "com.box",
		defaultAuth: "oauth-client-credentials-flow",
	},
	{
		id: "spotify",
		name: "Spotify Web API",
		description:
			"Search tracks, manage playlists, control playback, and read user libraries on Spotify",
		url: "https://api.apis.guru/v2/specs/spotify.com/sonallux/2023.2.27/openapi.json",
		idPrefix: "com.spotify",
		defaultAuth: "oauth-client-credentials-flow",
	},
	{
		id: "gitlab",
		name: "GitLab API",
		description: "Manage GitLab repositories, CI/CD pipelines, merge requests, issues, and users",
		url: "https://api.apis.guru/v2/specs/gitlab.com/v3/swagger.json",
		idPrefix: "com.gitlab",
		defaultAuth: "bearer",
	},
	{
		id: "netlify",
		name: "Netlify API",
		description: "Deploy sites, manage builds, configure domains, and handle forms on Netlify",
		url: "https://api.apis.guru/v2/specs/netlify.com/2.15.0/swagger.json",
		idPrefix: "com.netlify",
		defaultAuth: "oauth-client-credentials-flow",
	},
	{
		id: "launchdarkly",
		name: "LaunchDarkly API",
		description: "Create and manage feature flags, experiments, segments, and environments",
		url: "https://api.apis.guru/v2/specs/launchdarkly.com/5.3.0/swagger.json",
		idPrefix: "com.launchdarkly",
		defaultAuth: "apiKey",
	},
	{
		id: "postmark",
		name: "Postmark API",
		description:
			"Send and track transactional emails, manage templates and bounce handling via Postmark",
		url: "https://api.apis.guru/v2/specs/postmarkapp.com/server/1.0.0/swagger.json",
		idPrefix: "com.postmark",
		defaultAuth: "apiKey",
	},
	{
		id: "circleci",
		name: "CircleCI API",
		description: "Trigger pipelines, inspect workflows and jobs, and manage contexts and SSH keys",
		url: "https://api.apis.guru/v2/specs/circleci.com/v1/openapi.json",
		idPrefix: "com.circleci",
		defaultAuth: "apiKey",
	},
	{
		id: "grafana",
		name: "Grafana API",
		description: "Manage dashboards, alerts, datasources, users, and annotations in Grafana",
		url: "https://raw.githubusercontent.com/grafana/grafana/main/public/openapi3.json",
		idPrefix: "com.grafana",
		defaultAuth: "basic",
	},
	{
		id: "digitalocean",
		name: "DigitalOcean API",
		description:
			"Provision Droplets, Kubernetes clusters, databases, load balancers, and networking",
		url: "https://api.apis.guru/v2/specs/digitalocean.com/2.0/openapi.json",
		idPrefix: "com.digitalocean",
		defaultAuth: "bearer",
	},
	{
		id: "linode",
		name: "Linode (Akamai) API",
		description: "Manage cloud compute instances, volumes, Kubernetes clusters, and DNS via Linode",
		url: "https://api.apis.guru/v2/specs/linode.com/4.145.0/openapi.json",
		idPrefix: "com.linode",
		defaultAuth: "bearer",
	},
	{
		id: "square",
		name: "Square API",
		description: "Process payments, manage orders, catalog items, and bookings via Square",
		url: "https://api.apis.guru/v2/specs/squareup.com/2.0/openapi.json",
		idPrefix: "com.squareup",
		defaultAuth: "oauth-client-credentials-flow",
	},
	{
		id: "zendesk",
		name: "Zendesk Support API",
		description: "Manage support tickets, users, macros, triggers, and SLAs in Zendesk",
		url: "https://developer.zendesk.com/zendesk/oas.yaml",
		idPrefix: "com.zendesk",
		defaultAuth: "basic",
	},
	{
		id: "bitbucket",
		name: "Bitbucket API",
		description: "Manage Bitbucket repositories, pull requests, pipelines, and deployments",
		url: "https://api.apis.guru/v2/specs/bitbucket.org/2.0/openapi.yaml",
		idPrefix: "org.bitbucket",
		defaultAuth: "basic",
	},
	{
		id: "miro",
		name: "Miro API",
		description: "Create and manage Miro boards, frames, sticky notes, and collaborative widgets",
		url: "https://raw.githubusercontent.com/miroapp/api-clients/main/packages/generator/spec.json",
		idPrefix: "com.miro",
		defaultAuth: "bearer",
	},
	{
		id: "okta",
		name: "Okta Management API",
		description: "Manage users, groups, applications, policies, and identity providers via Okta",
		url: "https://raw.githubusercontent.com/okta/okta-management-openapi-spec/master/dist/current/management-oneOfInheritance.yaml",
		idPrefix: "com.okta",
		defaultAuth: "bearer",
	},
	{
		id: "meraki",
		name: "Cisco Meraki API",
		description: "Manage cloud-controlled Wi-Fi, switches, security cameras, and network policies",
		url: "https://api.apis.guru/v2/specs/meraki.com/0.0.0-streaming/openapi.json",
		idPrefix: "com.meraki",
		defaultAuth: "apiKey",
	},
	{
		id: "docker",
		name: "Docker Hub API",
		description:
			"Manage container image repositories, tags, webhooks, and access tokens on Docker Hub",
		url: "https://api.apis.guru/v2/specs/docker.com/hub/beta/openapi.json",
		idPrefix: "com.docker",
		defaultAuth: "bearer",
	},
	{
		id: "kubernetes",
		name: "Kubernetes API",
		description:
			"Manage pods, deployments, services, config maps, and cluster resources via the Kubernetes API",
		url: "https://api.apis.guru/v2/specs/kubernetes.io/unversioned/swagger.json",
		idPrefix: "io.kubernetes",
		defaultAuth: "bearer",
	},
	{
		id: "freshdesk",
		name: "Freshdesk API",
		description:
			"Manage support tickets, contacts, agents, and knowledge base articles in Freshdesk",
		url: "https://raw.githubusercontent.com/ccl-consulting/freshdesk-openapi-definitions/main/swagger.yaml",
		idPrefix: "com.freshdesk",
		defaultAuth: "basic",
	},
	{
		id: "dropbox",
		name: "Dropbox API",
		description: "Upload, download, share, and manage files and folders in Dropbox cloud storage",
		url: "https://api.apis.guru/v2/specs/dropbox.com/2/openapi.yaml",
		idPrefix: "com.dropbox",
		defaultAuth: "oauth-client-credentials-flow",
	},
	{
		id: "xero",
		name: "Xero Accounting API",
		description: "Manage invoices, contacts, bank accounts, and financial reporting in Xero",
		url: "https://raw.githubusercontent.com/XeroAPI/Xero-OpenAPI/master/xero_accounting.yaml",
		idPrefix: "com.xero",
		defaultAuth: "oauth-client-credentials-flow",
	},
	{
		id: "bigcommerce",
		name: "BigCommerce Catalog API",
		description: "Manage products, categories, brands, and variants in a BigCommerce store",
		url: "https://raw.githubusercontent.com/bigcommerce/api-specs/main/reference/catalog/products_catalog.v3.yml",
		idPrefix: "com.bigcommerce",
		defaultAuth: "apiKey",
	},
	{
		id: "recurly",
		name: "Recurly Billing API",
		description: "Manage subscriptions, accounts, invoices, and billing for recurring revenue",
		url: "https://raw.githubusercontent.com/recurly/recurly-client-node/master/openapi/api.yaml",
		idPrefix: "com.recurly",
		defaultAuth: "basic",
	},
	{
		id: "cohere",
		name: "Cohere AI API",
		description: "Access Cohere language AI models for chat, embeddings, and reranking",
		url: "https://raw.githubusercontent.com/cohere-ai/cohere-developer-experience/main/cohere-openapi.yaml",
		idPrefix: "com.cohere",
		defaultAuth: "bearer",
	},
	{
		id: "algolia",
		name: "Algolia Search API",
		description: "Search, configure indices, and manage records in Algolia",
		url: "https://raw.githubusercontent.com/algolia/api-clients-automation/main/docs/bundled/search.yml",
		idPrefix: "com.algolia",
		defaultAuth: "apiKey",
	},
	{
		id: "replicate",
		name: "Replicate API",
		description: "Run open-source machine learning models in the cloud via API",
		url: "https://api.replicate.com/openapi.json",
		idPrefix: "com.replicate",
		defaultAuth: "apiKey",
	},
	{
		id: "mixpanel",
		name: "Mixpanel Ingestion API",
		description: "Track events and update user profiles in Mixpanel for product analytics",
		url: "https://raw.githubusercontent.com/mixpanel/docs/main/openapi/src/ingestion.openapi.yaml",
		idPrefix: "com.mixpanel",
		defaultAuth: "basic",
	},
	{
		id: "trello",
		name: "Trello API",
		description: "Create and manage Trello boards, lists, cards, and team collaboration",
		url: "https://api.apis.guru/v2/specs/trello.com/1.0/openapi.json",
		idPrefix: "com.trello",
		defaultAuth: "oauth-client-credentials-flow",
	},
	{
		id: "confluence",
		name: "Confluence Cloud REST API",
		description:
			"Create, read, update, and manage pages, spaces, and content in Atlassian Confluence",
		url: "https://dac-static.atlassian.com/cloud/confluence/swagger.v3.json",
		idPrefix: "io.atlassian.confluence",
		defaultAuth: "bearer",
	},
	{
		id: "pipedrive",
		name: "Pipedrive CRM API",
		description: "Manage deals, contacts, pipelines, and sales activities in Pipedrive CRM",
		url: "https://developers.pipedrive.com/docs/api/v1/openapi.yaml",
		idPrefix: "com.pipedrive",
		defaultAuth: "apiKey",
	},
	{
		id: "adyen",
		name: "Adyen Checkout API",
		description: "Initiate and authorise online payments through the Adyen payment platform",
		url: "https://raw.githubusercontent.com/Adyen/adyen-openapi/master/yaml/CheckoutService-v71.yaml",
		idPrefix: "com.adyen",
		defaultAuth: "apiKey",
	},
	{
		id: "twilio-voice",
		name: "Twilio Voice API",
		description: "Make, receive, and control phone calls programmatically using Twilio Voice",
		url: "https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_voice_v1.json",
		idPrefix: "io.twilio.voice",
		defaultAuth: "basic",
	},
	{
		id: "paddle",
		name: "Paddle Billing API",
		description: "Manage subscriptions, payments, customers, and transactions with Paddle",
		url: "https://raw.githubusercontent.com/PaddleHQ/paddle-openapi/main/v1/openapi.yaml",
		idPrefix: "com.paddle",
		defaultAuth: "bearer",
	},
	{
		id: "lob",
		name: "Lob API",
		description: "Send physical mail — letters, postcards, and checks — programmatically via API",
		url: "https://raw.githubusercontent.com/lob/lob-openapi/main/lob-api-public.yml",
		idPrefix: "com.lob",
		defaultAuth: "basic",
	},
	{
		id: "deepl",
		name: "DeepL Translation API",
		description:
			"Translate text and documents into 30+ languages using DeepL neural machine translation",
		url: "https://raw.githubusercontent.com/DeepLcom/openapi/main/openapi.yaml",
		idPrefix: "com.deepl",
		defaultAuth: "apiKey",
	},
	{
		id: "docusign",
		name: "DocuSign eSignature API",
		description: "Send, sign, and manage electronic signature agreements and envelopes",
		url: "https://raw.githubusercontent.com/docusign/OpenAPI-Specifications/master/esignature.rest.swagger-v2.1.json",
		idPrefix: "com.docusign",
		defaultAuth: "oauth-client-credentials-flow",
	},
	{
		id: "chargebee",
		name: "Chargebee Billing API",
		description: "Manage subscriptions, invoices, customers, and revenue operations with Chargebee",
		url: "https://raw.githubusercontent.com/chargebee/openapi/master/spec/chargebee_api_v2_pc_v1_spec.json",
		idPrefix: "com.chargebee",
		defaultAuth: "basic",
	},
	{
		id: "twilio-video",
		name: "Twilio Video API",
		description: "Build real-time video and audio communication features using Twilio Video",
		url: "https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_video_v1.json",
		idPrefix: "io.twilio.video",
		defaultAuth: "basic",
	},
	{
		id: "cloudinary",
		name: "Cloudinary Media API",
		description:
			"Upload, transform, optimize, and deliver images and videos via the Cloudinary platform",
		url: "https://raw.githubusercontent.com/cloudinary/account-provisioning-java/master/api/openapi.yaml",
		idPrefix: "com.cloudinary",
		defaultAuth: "basic",
	},
	{
		id: "amplitude",
		name: "Amplitude Analytics API",
		description: "Track events, query analytics data, and manage user cohorts in Amplitude",
		url: "https://raw.githubusercontent.com/amplitude/amplitude-docs/main/content/collections/api/en/session-replay-openapi.yaml",
		idPrefix: "com.amplitude",
		defaultAuth: "basic",
	},
]

export function getCatalogEntry(id: string): CatalogEntry | undefined {
	return CATALOG.find((e) => e.id === id)
}
