// Auto-generated by scripts/generate-camunda-spec.mjs — do not edit manually.
// Re-run: node scripts/generate-camunda-spec.mjs

export interface MethodSpec {
	description: string
	endpoint: string
	params: string
	returns: string
}

export const CAMUNDA_SPEC: Record<string, Record<string, MethodSpec>> = {
	auditLog: {
		searchAuditLogs: {
			description: "Search audit logs Search for audit logs based on given criteria.",
			endpoint: "POST /audit-logs/search",
			params: "body?: AuditLogSearchQueryRequest",
			returns: "AuditLogSearchQueryResult",
		},
		getAuditLog: {
			description: "Get audit log Get an audit log entry by auditLogKey.",
			endpoint: "GET /audit-logs/{auditLogKey}",
			params: "auditLogKey: string",
			returns: "AuditLogResult",
		},
	},
	authentication: {
		getAuthentication: {
			description: "Get current user Retrieves the current authenticated user.",
			endpoint: "GET /authentication/me",
			params: "none",
			returns: "CamundaUserResult",
		},
	},
	authorization: {
		createAuthorization: {
			description: "Create authorization Create the authorization.",
			endpoint: "POST /authorizations",
			params: "body: AuthorizationRequest",
			returns: "AuthorizationCreateResult",
		},
		searchAuthorizations: {
			description: "Search authorizations Search for authorizations based on given criteria.",
			endpoint: "POST /authorizations/search",
			params: "body?: AuthorizationSearchQuery",
			returns: "AuthorizationSearchResult",
		},
		getAuthorization: {
			description: "Get authorization Get authorization by the given key.",
			endpoint: "GET /authorizations/{authorizationKey}",
			params: "authorizationKey: string",
			returns: "AuthorizationResult",
		},
		updateAuthorization: {
			description: "Update authorization Update the authorization with the given key.",
			endpoint: "PUT /authorizations/{authorizationKey}",
			params: "authorizationKey: string, body: AuthorizationRequest",
			returns: "void",
		},
		deleteAuthorization: {
			description: "Delete authorization Deletes the authorization with the given key.",
			endpoint: "DELETE /authorizations/{authorizationKey}",
			params: "authorizationKey: string",
			returns: "void",
		},
	},
	batchOperation: {
		searchBatchOperationItems: {
			description:
				"Search batch operation items Search for batch operation items based on given criteria.",
			endpoint: "POST /batch-operation-items/search",
			params: "body?: BatchOperationItemSearchQuery",
			returns: "BatchOperationItemSearchQueryResult",
		},
		searchBatchOperations: {
			description: "Search batch operations Search for batch operations based on given criteria.",
			endpoint: "POST /batch-operations/search",
			params: "body?: BatchOperationSearchQuery",
			returns: "BatchOperationSearchQueryResult",
		},
		getBatchOperation: {
			description: "Get batch operation Get batch operation by key.",
			endpoint: "GET /batch-operations/{batchOperationKey}",
			params: "batchOperationKey: string",
			returns: "BatchOperationResponse",
		},
		cancelBatchOperation: {
			description:
				"Cancel Batch operation Cancels a running batch operation. This is done asynchronously, the progress can be tracked using the batch operation status endpoint (/batch-operations/{batchOperationKey}).",
			endpoint: "POST /batch-operations/{batchOperationKey}/cancellation",
			params: "batchOperationKey: string",
			returns: "void",
		},
		resumeBatchOperation: {
			description:
				"Resume Batch operation Resumes a suspended batch operation. This is done asynchronously, the progress can be tracked using the batch operation status endpoint (/batch-operations/{batchOperationKey}).",
			endpoint: "POST /batch-operations/{batchOperationKey}/resumption",
			params: "batchOperationKey: string",
			returns: "void",
		},
		suspendBatchOperation: {
			description:
				"Suspend Batch operation Suspends a running batch operation. This is done asynchronously, the progress can be tracked using the batch operation status endpoint (/batch-operations/{batchOperationKey}).",
			endpoint: "POST /batch-operations/{batchOperationKey}/suspension",
			params: "batchOperationKey: string",
			returns: "void",
		},
	},
	clock: {
		pinClock: {
			description:
				"Pin internal clock (alpha) Set a precise, static time for the Zeebe engine's internal clock. When the clock is pinned, it remains at the specified time and does not advance. To change the time, the clock must be pinned again with a new timestamp.",
			endpoint: "PUT /clock",
			params: "body: ClockPinRequest",
			returns: "void",
		},
		resetClock: {
			description:
				"Reset internal clock (alpha) Resets the Zeebe engine's internal clock to the current system time, enabling it to tick in real-time. This operation is useful for returning the clock to normal behavior after it has been pinned to a specific time.",
			endpoint: "POST /clock/reset",
			params: "none",
			returns: "void",
		},
	},
	clusterVariable: {
		createGlobalClusterVariable: {
			description:
				"Create a global-scoped cluster variable Create a global-scoped cluster variable.",
			endpoint: "POST /cluster-variables/global",
			params: "body: CreateClusterVariableRequest",
			returns: "ClusterVariableResult",
		},
		getGlobalClusterVariable: {
			description: "Get a global-scoped cluster variable Get a global-scoped cluster variable.",
			endpoint: "GET /cluster-variables/global/{name}",
			params: "name: string",
			returns: "ClusterVariableResult",
		},
		updateGlobalClusterVariable: {
			description:
				"Update a global-scoped cluster variable Updates the value of an existing global cluster variable. The variable must exist, otherwise a 404 error is returned.",
			endpoint: "PUT /cluster-variables/global/{name}",
			params: "name: string, body: UpdateClusterVariableRequest",
			returns: "ClusterVariableResult",
		},
		deleteGlobalClusterVariable: {
			description:
				"Delete a global-scoped cluster variable Delete a global-scoped cluster variable.",
			endpoint: "DELETE /cluster-variables/global/{name}",
			params: "name: string",
			returns: "void",
		},
		searchClusterVariables: {
			description:
				"Search for cluster variables based on given criteria. By default, long variable values in the response are truncated.",
			endpoint: "POST /cluster-variables/search",
			params: "body?: ClusterVariableSearchQueryRequest, query?: { truncateValues?: boolean }",
			returns: "ClusterVariableSearchQueryResult",
		},
		createTenantClusterVariable: {
			description:
				"Create a tenant-scoped cluster variable Create a new cluster variable for the given tenant.",
			endpoint: "POST /cluster-variables/tenants/{tenantId}",
			params: "tenantId: string, body: CreateClusterVariableRequest",
			returns: "ClusterVariableResult",
		},
		getTenantClusterVariable: {
			description: "Get a tenant-scoped cluster variable Get a tenant-scoped cluster variable.",
			endpoint: "GET /cluster-variables/tenants/{tenantId}/{name}",
			params: "tenantId: string, name: string",
			returns: "ClusterVariableResult",
		},
		updateTenantClusterVariable: {
			description:
				"Update a tenant-scoped cluster variable Updates the value of an existing tenant-scoped cluster variable. The variable must exist, otherwise a 404 error is returned.",
			endpoint: "PUT /cluster-variables/tenants/{tenantId}/{name}",
			params: "tenantId: string, name: string, body: UpdateClusterVariableRequest",
			returns: "ClusterVariableResult",
		},
		deleteTenantClusterVariable: {
			description:
				"Delete a tenant-scoped cluster variable Delete a tenant-scoped cluster variable.",
			endpoint: "DELETE /cluster-variables/tenants/{tenantId}/{name}",
			params: "tenantId: string, name: string",
			returns: "void",
		},
	},
	conditional: {
		evaluateConditionals: {
			description:
				"Evaluate root level conditional start events Evaluates root-level conditional start events for process definitions. If the evaluation is successful, it will return the keys of all created process instances, along with their associated process definition key. Multiple root-level conditional start events of the same process definition can trigger if their conditions evaluate to true.",
			endpoint: "POST /conditionals/evaluation",
			params: "body: ConditionalEvaluationInstruction",
			returns: "EvaluateConditionalResult",
		},
	},
	messageSubscription: {
		searchCorrelatedMessageSubscriptions: {
			description:
				"Search correlated message subscriptions Search correlated message subscriptions based on given criteria.",
			endpoint: "POST /correlated-message-subscriptions/search",
			params: "body?: CorrelatedMessageSubscriptionSearchQuery",
			returns: "CorrelatedMessageSubscriptionSearchQueryResult",
		},
		searchMessageSubscriptions: {
			description:
				"Search message subscriptions Search for message subscriptions based on given criteria.",
			endpoint: "POST /message-subscriptions/search",
			params: "body?: MessageSubscriptionSearchQuery",
			returns: "MessageSubscriptionSearchQueryResult",
		},
	},
	decisionDefinition: {
		evaluateDecision: {
			description:
				"Evaluate decision Evaluates a decision. You specify the decision to evaluate either by using its unique key (as returned by DeployResource), or using the decision ID. When using the decision ID, the latest deployed",
			endpoint: "POST /decision-definitions/evaluation",
			params: "body: DecisionEvaluationInstruction",
			returns: "EvaluateDecisionResult",
		},
		searchDecisionDefinitions: {
			description:
				"Search decision definitions Search for decision definitions based on given criteria.",
			endpoint: "POST /decision-definitions/search",
			params: "body?: DecisionDefinitionSearchQuery",
			returns: "DecisionDefinitionSearchQueryResult",
		},
		getDecisionDefinition: {
			description: "Get decision definition Returns a decision definition by key.",
			endpoint: "GET /decision-definitions/{decisionDefinitionKey}",
			params: "decisionDefinitionKey: string",
			returns: "DecisionDefinitionResult",
		},
		getDecisionDefinitionXML: {
			description: "Get decision definition XML Returns decision definition as XML.",
			endpoint: "GET /decision-definitions/{decisionDefinitionKey}/xml",
			params: "decisionDefinitionKey: string",
			returns: "void",
		},
	},
	decisionInstance: {
		searchDecisionInstances: {
			description:
				"Search decision instances Search for decision instances based on given criteria.",
			endpoint: "POST /decision-instances/search",
			params: "body?: DecisionInstanceSearchQuery",
			returns: "DecisionInstanceSearchQueryResult",
		},
		getDecisionInstance: {
			description: "Get decision instance Returns a decision instance.",
			endpoint: "GET /decision-instances/{decisionEvaluationInstanceKey}",
			params: "decisionEvaluationInstanceKey: string",
			returns: "DecisionInstanceGetQueryResult",
		},
		deleteDecisionInstancesBatchOperation: {
			description:
				"Delete decision instances (batch) Delete multiple decision instances. This will delete the historic data from secondary storage. This is done asynchronously, the progress can be tracked using the batchOperationKey from the response and the batch operation status endpoint (/batch-operations/{batchOperationKey}).",
			endpoint: "POST /decision-instances/deletion",
			params: "body: DecisionInstanceDeletionBatchOperationRequest",
			returns: "BatchOperationCreatedResult",
		},
	},
	decisionRequirements: {
		searchDecisionRequirements: {
			description:
				"Search decision requirements Search for decision requirements based on given criteria.",
			endpoint: "POST /decision-requirements/search",
			params: "body?: DecisionRequirementsSearchQuery",
			returns: "DecisionRequirementsSearchQueryResult",
		},
		getDecisionRequirements: {
			description: "Get decision requirements Returns Decision Requirements as JSON.",
			endpoint: "GET /decision-requirements/{decisionRequirementsKey}",
			params: "decisionRequirementsKey: string",
			returns: "DecisionRequirementsResult",
		},
		getDecisionRequirementsXML: {
			description: "Get decision requirements XML Returns decision requirements as XML.",
			endpoint: "GET /decision-requirements/{decisionRequirementsKey}/xml",
			params: "decisionRequirementsKey: string",
			returns: "void",
		},
	},
	resource: {
		createDeployment: {
			description:
				"Deploy resources Deploys one or more resources (e.g. processes, decision models, or forms). This is an atomic call, i.e. either all resources are deployed or none of them are.",
			endpoint: "POST /deployments",
			params: "none",
			returns: "DeploymentResult",
		},
		getResource: {
			description:
				"Get resource Returns a deployed resource. :::info Currently, this endpoint only supports RPA resources.",
			endpoint: "GET /resources/{resourceKey}",
			params: "resourceKey: string",
			returns: "ResourceResult",
		},
		getResourceContent: {
			description:
				"Get resource content Returns the content of a deployed resource. :::info Currently, this endpoint only supports RPA resources.",
			endpoint: "GET /resources/{resourceKey}/content",
			params: "resourceKey: string",
			returns: "string",
		},
		deleteResource: {
			description:
				"Delete resource Deletes a deployed resource. This can be a process definition, decision requirements definition, or form definition deployed using the deploy resources endpoint. Specify the resource you want to delete in the `resourceKey` parameter.",
			endpoint: "POST /resources/{resourceKey}/deletion",
			params: "resourceKey: string, body?: DeleteResourceRequest",
			returns: "DeleteResourceResponse",
		},
	},
	document: {
		createDocument: {
			description:
				"Upload document Upload a document to the Camunda 8 cluster. Note that this is currently supported for document stores of type: AWS, GCP, in-memory (non-production), local (non-production)",
			endpoint: "POST /documents",
			params: "query?: { storeId?: string; documentId?: DocumentId }",
			returns: "DocumentReference",
		},
		createDocuments: {
			description:
				"Upload multiple documents Upload multiple documents to the Camunda 8 cluster. The caller must provide a file name for each document, which will be used in case of a multi-status response",
			endpoint: "POST /documents/batch",
			params: "query?: { storeId?: string }",
			returns: "DocumentCreationBatchResponse",
		},
		getDocument: {
			description:
				"Download document Download a document from the Camunda 8 cluster. Note that this is currently supported for document stores of type: AWS, GCP, in-memory (non-production), local (non-production)",
			endpoint: "GET /documents/{documentId}",
			params: "documentId: string, query?: { storeId?: string; contentHash?: string }",
			returns: "void",
		},
		deleteDocument: {
			description:
				"Delete document Delete a document from the Camunda 8 cluster. Note that this is currently supported for document stores of type: AWS, GCP, in-memory (non-production), local (non-production)",
			endpoint: "DELETE /documents/{documentId}",
			params: "documentId: string, query?: { storeId?: string }",
			returns: "void",
		},
		createDocumentLink: {
			description:
				"Create document link Create a link to a document in the Camunda 8 cluster. Note that this is currently supported for document stores of type: AWS, GCP",
			endpoint: "POST /documents/{documentId}/links",
			params:
				"documentId: string, body?: DocumentLinkRequest, query?: { storeId?: string; contentHash?: string }",
			returns: "DocumentLink",
		},
	},
	adHocSubProcess: {
		activateAdHocSubProcessActivities: {
			description:
				"Activate activities within an ad-hoc sub-process Activates selected activities within an ad-hoc sub-process identified by element ID. The provided element IDs must exist within the ad-hoc sub-process instance identified by the provided adHocSubProcessInstanceKey.",
			endpoint: "POST /element-instances/ad-hoc-activities/{adHocSubProcessInstanceKey}/activation",
			params:
				"adHocSubProcessInstanceKey: string, body: AdHocSubProcessActivateActivitiesInstruction",
			returns: "void",
		},
	},
	elementInstance: {
		searchElementInstances: {
			description: "Search element instances Search for element instances based on given criteria.",
			endpoint: "POST /element-instances/search",
			params: "body?: ElementInstanceSearchQuery",
			returns: "ElementInstanceSearchQueryResult",
		},
		getElementInstance: {
			description: "Get element instance Returns element instance as JSON.",
			endpoint: "GET /element-instances/{elementInstanceKey}",
			params: "elementInstanceKey: string",
			returns: "ElementInstanceResult",
		},
		searchElementInstanceIncidents: {
			description:
				"Search for incidents of a specific element instance Search for incidents caused by the specified element instance, including incidents of any child instances created from this element instance. Although the `elementInstanceKey` is provided as a path parameter to indicate the root element instance,",
			endpoint: "POST /element-instances/{elementInstanceKey}/incidents/search",
			params: "elementInstanceKey: string, body: IncidentSearchQuery",
			returns: "IncidentSearchQueryResult",
		},
		createElementInstanceVariables: {
			description:
				"Update element instance variables Updates all the variables of a particular scope (for example, process instance, element instance) with the given variable data. Specify the element instance in the `elementInstanceKey` parameter.",
			endpoint: "PUT /element-instances/{elementInstanceKey}/variables",
			params: "elementInstanceKey: string, body: SetVariableRequest",
			returns: "void",
		},
	},
	expression: {
		evaluateExpression: {
			description:
				"Evaluate an expression Evaluates a FEEL expression and returns the result. Supports references to tenant scoped cluster variables when a tenant ID is provided.",
			endpoint: "POST /expression/evaluation",
			params: "body: ExpressionEvaluationRequest",
			returns: "ExpressionEvaluationResult",
		},
	},
	globalListener: {
		createGlobalTaskListener: {
			description: "Create global user task listener Create a new global user task listener.",
			endpoint: "POST /global-task-listeners",
			params: "body: CreateGlobalTaskListenerRequest",
			returns: "GlobalTaskListenerResult",
		},
		getGlobalTaskListener: {
			description: "Get global user task listener Get a global user task listener by its id.",
			endpoint: "GET /global-task-listeners/{id}",
			params: "id: string",
			returns: "GlobalTaskListenerResult",
		},
		updateGlobalTaskListener: {
			description: "Update global user task listener Updates a global user task listener.",
			endpoint: "PUT /global-task-listeners/{id}",
			params: "id: string, body: UpdateGlobalTaskListenerRequest",
			returns: "GlobalTaskListenerResult",
		},
		deleteGlobalTaskListener: {
			description: "Delete global user task listener Deletes a global user task listener.",
			endpoint: "DELETE /global-task-listeners/{id}",
			params: "id: string",
			returns: "void",
		},
		searchGlobalTaskListeners: {
			description:
				"Search global user task listeners Search for global user task listeners based on given criteria.",
			endpoint: "POST /global-task-listeners/search",
			params: "body?: GlobalTaskListenerSearchQueryRequest",
			returns: "GlobalTaskListenerSearchQueryResult",
		},
	},
	group: {
		createGroup: {
			description: "Create group Create a new group.",
			endpoint: "POST /groups",
			params: "body?: GroupCreateRequest",
			returns: "GroupCreateResult",
		},
		searchGroups: {
			description: "Search groups Search for groups based on given criteria.",
			endpoint: "POST /groups/search",
			params: "body?: GroupSearchQueryRequest",
			returns: "GroupSearchQueryResult",
		},
		getGroup: {
			description: "Get group Get a group by its ID.",
			endpoint: "GET /groups/{groupId}",
			params: "groupId: string",
			returns: "GroupResult",
		},
		updateGroup: {
			description: "Update group Update a group with the given ID.",
			endpoint: "PUT /groups/{groupId}",
			params: "groupId: string, body: GroupUpdateRequest",
			returns: "GroupUpdateResult",
		},
		deleteGroup: {
			description: "Delete group Deletes the group with the given ID.",
			endpoint: "DELETE /groups/{groupId}",
			params: "groupId: string",
			returns: "void",
		},
		searchClientsForGroup: {
			description: "Search group clients Search clients assigned to a group.",
			endpoint: "POST /groups/{groupId}/clients/search",
			params: "groupId: string, body?: GroupClientSearchQueryRequest",
			returns: "GroupClientSearchResult",
		},
		assignClientToGroup: {
			description:
				"Assign a client to a group Assigns a client to a group, making it a member of the group. Members of the group inherit the group authorizations, roles, and tenant assignments.",
			endpoint: "PUT /groups/{groupId}/clients/{clientId}",
			params: "groupId: string, clientId: string",
			returns: "void",
		},
		unassignClientFromGroup: {
			description:
				"Unassign a client from a group Unassigns a client from a group. The client is removed as a group member, with associated authorizations, roles, and tenant assignments no longer applied.",
			endpoint: "DELETE /groups/{groupId}/clients/{clientId}",
			params: "groupId: string, clientId: string",
			returns: "void",
		},
		searchMappingRulesForGroup: {
			description: "Search group mapping rules Search mapping rules assigned to a group.",
			endpoint: "POST /groups/{groupId}/mapping-rules/search",
			params: "groupId: string, body?: MappingRuleSearchQueryRequest",
			returns: "GroupMappingRuleSearchResult",
		},
		assignMappingRuleToGroup: {
			description: "Assign a mapping rule to a group Assigns a mapping rule to a group.",
			endpoint: "PUT /groups/{groupId}/mapping-rules/{mappingRuleId}",
			params: "groupId: string, mappingRuleId: string",
			returns: "void",
		},
		unassignMappingRuleFromGroup: {
			description: "Unassign a mapping rule from a group Unassigns a mapping rule from a group.",
			endpoint: "DELETE /groups/{groupId}/mapping-rules/{mappingRuleId}",
			params: "groupId: string, mappingRuleId: string",
			returns: "void",
		},
		searchRolesForGroup: {
			description: "Search group roles Search roles assigned to a group.",
			endpoint: "POST /groups/{groupId}/roles/search",
			params: "groupId: string, body?: RoleSearchQueryRequest",
			returns: "GroupRoleSearchResult",
		},
		searchUsersForGroup: {
			description: "Search group users Search users assigned to a group.",
			endpoint: "POST /groups/{groupId}/users/search",
			params: "groupId: string, body?: GroupUserSearchQueryRequest",
			returns: "GroupUserSearchResult",
		},
		assignUserToGroup: {
			description:
				"Assign a user to a group Assigns a user to a group, making the user a member of the group. Group members inherit the group authorizations, roles, and tenant assignments.",
			endpoint: "PUT /groups/{groupId}/users/{username}",
			params: "groupId: string, username: string",
			returns: "void",
		},
		unassignUserFromGroup: {
			description:
				"Unassign a user from a group Unassigns a user from a group. The user is removed as a group member, with associated authorizations, roles, and tenant assignments no longer applied.",
			endpoint: "DELETE /groups/{groupId}/users/{username}",
			params: "groupId: string, username: string",
			returns: "void",
		},
	},
	incident: {
		searchIncidents: {
			description: "Search incidents Search for incidents based on given criteria.",
			endpoint: "POST /incidents/search",
			params: "body?: IncidentSearchQuery",
			returns: "IncidentSearchQueryResult",
		},
		getIncident: {
			description: "Get incident Returns incident as JSON.",
			endpoint: "GET /incidents/{incidentKey}",
			params: "incidentKey: string",
			returns: "IncidentResult",
		},
		resolveIncident: {
			description:
				"Resolve incident Marks the incident as resolved; most likely a call to Update job will be necessary to reset the job's retries, followed by this call.",
			endpoint: "POST /incidents/{incidentKey}/resolution",
			params: "incidentKey: string, body?: IncidentResolutionRequest",
			returns: "void",
		},
		getProcessInstanceStatisticsByDefinition: {
			description:
				"Get process instance statistics by definition Returns statistics for active process instances with incidents, grouped by process definition. The result set is scoped to a specific incident error hash code, which must be provided as a filter in the request body.",
			endpoint: "POST /incidents/statistics/process-instances-by-definition",
			params: "body: IncidentProcessInstanceStatisticsByDefinitionQuery",
			returns: "IncidentProcessInstanceStatisticsByDefinitionQueryResult",
		},
		getProcessInstanceStatisticsByError: {
			description:
				"Get process instance statistics by error Returns statistics for active process instances that currently have active incidents, grouped by incident error hash code.",
			endpoint: "POST /incidents/statistics/process-instances-by-error",
			params: "body?: IncidentProcessInstanceStatisticsByErrorQuery",
			returns: "IncidentProcessInstanceStatisticsByErrorQueryResult",
		},
	},
	job: {
		activateJobs: {
			description:
				"Activate jobs Iterate through all known partitions and activate jobs up to the requested maximum.",
			endpoint: "POST /jobs/activation",
			params: "body: JobActivationRequest",
			returns: "JobActivationResult",
		},
		searchJobs: {
			description: "Search jobs Search for jobs based on given criteria.",
			endpoint: "POST /jobs/search",
			params: "body?: JobSearchQuery",
			returns: "JobSearchQueryResult",
		},
		updateJob: {
			description: "Update job Update a job with the given key.",
			endpoint: "PATCH /jobs/{jobKey}",
			params: "jobKey: string, body: JobUpdateRequest",
			returns: "void",
		},
		completeJob: {
			description:
				"Complete job Complete a job with the given payload, which allows completing the associated service task.",
			endpoint: "POST /jobs/{jobKey}/completion",
			params: "jobKey: string, body?: JobCompletionRequest",
			returns: "void",
		},
		throwJobError: {
			description:
				"Throw error for job Reports a business error (i.e. non-technical) that occurs while processing a job.",
			endpoint: "POST /jobs/{jobKey}/error",
			params: "jobKey: string, body: JobErrorRequest",
			returns: "void",
		},
		failJob: {
			description: "Fail job Mark the job as failed.",
			endpoint: "POST /jobs/{jobKey}/failure",
			params: "jobKey: string, body?: JobFailRequest",
			returns: "void",
		},
		getGlobalJobStatistics: {
			description:
				"Global job statistics Returns global aggregated counts for jobs. Optionally filter by the creation time window and/or jobType.",
			endpoint: "GET /jobs/statistics/global",
			params: "query?: { from: string; to: string; jobType?: string }",
			returns: "GlobalJobStatisticsQueryResult",
		},
		getJobTypeStatistics: {
			description: "Get job statistics by type Get statistics about jobs, grouped by job type.",
			endpoint: "POST /jobs/statistics/by-types",
			params: "body: JobTypeStatisticsQuery",
			returns: "JobTypeStatisticsQueryResult",
		},
		getJobWorkerStatistics: {
			description:
				"Get job statistics by worker Returns aggregated metrics per worker for the given jobType.",
			endpoint: "POST /jobs/statistics/by-workers",
			params: "body: JobWorkerStatisticsQuery",
			returns: "JobWorkerStatisticsQueryResult",
		},
		getJobTimeSeriesStatistics: {
			description:
				"Get time-series metrics for a job type Returns a list of time-bucketed metrics ordered ascending by time. The `from` and `to` fields select the time window of interest. Each item in the response corresponds to one time bucket of the requested resolution.",
			endpoint: "POST /jobs/statistics/time-series",
			params: "body: JobTimeSeriesStatisticsQuery",
			returns: "JobTimeSeriesStatisticsQueryResult",
		},
	},
	license: {
		getLicense: {
			description: "Get license status Obtains the status of the current Camunda license.",
			endpoint: "GET /license",
			params: "none",
			returns: "LicenseResponse",
		},
	},
	mappingRule: {
		createMappingRule: {
			description: "Create mapping rule Create a new mapping rule",
			endpoint: "POST /mapping-rules",
			params: "body?: MappingRuleCreateRequest",
			returns: "MappingRuleCreateResult",
		},
		searchMappingRule: {
			description: "Search mapping rules Search for mapping rules based on given criteria.",
			endpoint: "POST /mapping-rules/search",
			params: "body?: MappingRuleSearchQueryRequest",
			returns: "MappingRuleSearchQueryResult",
		},
		getMappingRule: {
			description: "Get a mapping rule Gets the mapping rule with the given ID.",
			endpoint: "GET /mapping-rules/{mappingRuleId}",
			params: "mappingRuleId: string",
			returns: "MappingRuleResult",
		},
		updateMappingRule: {
			description: "Update mapping rule Update a mapping rule.",
			endpoint: "PUT /mapping-rules/{mappingRuleId}",
			params: "mappingRuleId: string, body?: MappingRuleUpdateRequest",
			returns: "MappingRuleUpdateResult",
		},
		deleteMappingRule: {
			description: "Delete a mapping rule Deletes the mapping rule with the given ID.",
			endpoint: "DELETE /mapping-rules/{mappingRuleId}",
			params: "mappingRuleId: string",
			returns: "void",
		},
	},
	message: {
		correlateMessage: {
			description:
				"Correlate message Publishes a message and correlates it to a subscription. If correlation is successful it will return the first process instance key the message correlated with. The message is not buffered.",
			endpoint: "POST /messages/correlation",
			params: "body: MessageCorrelationRequest",
			returns: "MessageCorrelationResult",
		},
		publishMessage: {
			description:
				"Publish message Publishes a single message. Messages are published to specific partitions computed from their correlation keys. Messages can be buffered.",
			endpoint: "POST /messages/publication",
			params: "body: MessagePublicationRequest",
			returns: "MessagePublicationResult",
		},
	},
	processDefinition: {
		searchProcessDefinitions: {
			description:
				"Search process definitions Search for process definitions based on given criteria.",
			endpoint: "POST /process-definitions/search",
			params: "body?: ProcessDefinitionSearchQuery",
			returns: "ProcessDefinitionSearchQueryResult",
		},
		getProcessDefinitionMessageSubscriptionStatistics: {
			description:
				"Get message subscription statistics Get message subscription statistics, grouped by process definition.",
			endpoint: "POST /process-definitions/statistics/message-subscriptions",
			params: "body?: ProcessDefinitionMessageSubscriptionStatisticsQuery",
			returns: "ProcessDefinitionMessageSubscriptionStatisticsQueryResult",
		},
		getProcessDefinitionInstanceStatistics: {
			description:
				"Get process instance statistics Get statistics about process instances, grouped by process definition and tenant.",
			endpoint: "POST /process-definitions/statistics/process-instances",
			params: "body?: ProcessDefinitionInstanceStatisticsQuery",
			returns: "ProcessDefinitionInstanceStatisticsQueryResult",
		},
		getProcessDefinition: {
			description: "Get process definition Returns process definition as JSON.",
			endpoint: "GET /process-definitions/{processDefinitionKey}",
			params: "processDefinitionKey: string",
			returns: "ProcessDefinitionResult",
		},
		getStartProcessForm: {
			description:
				"Get process start form Get the start form of a process. Note that this endpoint will only return linked forms. This endpoint does not support embedded forms.",
			endpoint: "GET /process-definitions/{processDefinitionKey}/form",
			params: "processDefinitionKey: string",
			returns: "FormResult",
		},
		getProcessDefinitionStatistics: {
			description:
				"Get process definition statistics Get statistics about elements in currently running process instances by process definition key and search filter.",
			endpoint: "POST /process-definitions/{processDefinitionKey}/statistics/element-instances",
			params: "processDefinitionKey: string, body?: ProcessDefinitionElementStatisticsQuery",
			returns: "ProcessDefinitionElementStatisticsQueryResult",
		},
		getProcessDefinitionXML: {
			description: "Get process definition XML Returns process definition as XML.",
			endpoint: "GET /process-definitions/{processDefinitionKey}/xml",
			params: "processDefinitionKey: string",
			returns: "void",
		},
		getProcessDefinitionInstanceVersionStatistics: {
			description:
				"Get process instance statistics by version Get statistics about process instances, grouped by version for a given process definition. The process definition ID must be provided as a required field in the request body filter.",
			endpoint: "POST /process-definitions/statistics/process-instances-by-version",
			params: "body: ProcessDefinitionInstanceVersionStatisticsQuery",
			returns: "ProcessDefinitionInstanceVersionStatisticsQueryResult",
		},
	},
	processInstance: {
		createProcessInstance: {
			description:
				"Create process instance Creates and starts an instance of the specified process. The process definition to use to create the instance can be specified either using its unique key (as returned by Deploy resources), or using the BPMN process id and a version.",
			endpoint: "POST /process-instances",
			params: "body: ProcessInstanceCreationInstruction",
			returns: "CreateProcessInstanceResult",
		},
		cancelProcessInstancesBatchOperation: {
			description:
				"Cancel process instances (batch) Cancels multiple running process instances. Since only ACTIVE root instances can be cancelled, any given filters for state and parentProcessInstanceKey are ignored and overridden during this batch operation.",
			endpoint: "POST /process-instances/cancellation",
			params: "body: ProcessInstanceCancellationBatchOperationRequest",
			returns: "BatchOperationCreatedResult",
		},
		deleteProcessInstancesBatchOperation: {
			description:
				"Delete process instances (batch) Delete multiple process instances. This will delete the historic data from secondary storage. Only process instances in a final state (COMPLETED or TERMINATED) can be deleted. This is done asynchronously, the progress can be tracked using the batchOperationKey from the response and the batch operation status endpoint (/batch-operations/{batchOperationKey}).",
			endpoint: "POST /process-instances/deletion",
			params: "body: ProcessInstanceDeletionBatchOperationRequest",
			returns: "BatchOperationCreatedResult",
		},
		resolveIncidentsBatchOperation: {
			description:
				"Resolve related incidents (batch) Resolves multiple instances of process instances. Since only process instances with ACTIVE state can have unresolved incidents, any given filters for state are ignored and overridden during this batch operation.",
			endpoint: "POST /process-instances/incident-resolution",
			params: "body?: ProcessInstanceIncidentResolutionBatchOperationRequest",
			returns: "BatchOperationCreatedResult",
		},
		migrateProcessInstancesBatchOperation: {
			description:
				"Migrate process instances (batch) Migrate multiple process instances. Since only process instances with ACTIVE state can be migrated, any given filters for state are ignored and overridden during this batch operation.",
			endpoint: "POST /process-instances/migration",
			params: "body: ProcessInstanceMigrationBatchOperationRequest",
			returns: "BatchOperationCreatedResult",
		},
		modifyProcessInstancesBatchOperation: {
			description:
				"Modify process instances (batch) Modify multiple process instances. Since only process instances with ACTIVE state can be modified, any given filters for state are ignored and overridden during this batch operation.",
			endpoint: "POST /process-instances/modification",
			params: "body: ProcessInstanceModificationBatchOperationRequest",
			returns: "BatchOperationCreatedResult",
		},
		searchProcessInstances: {
			description: "Search process instances Search for process instances based on given criteria.",
			endpoint: "POST /process-instances/search",
			params: "body?: ProcessInstanceSearchQuery",
			returns: "ProcessInstanceSearchQueryResult",
		},
		getProcessInstance: {
			description: "Get process instance Get the process instance by the process instance key.",
			endpoint: "GET /process-instances/{processInstanceKey}",
			params: "processInstanceKey: string",
			returns: "ProcessInstanceResult",
		},
		getProcessInstanceCallHierarchy: {
			description:
				"Get call hierarchy Returns the call hierarchy for a given process instance, showing its ancestry up to the root instance.",
			endpoint: "GET /process-instances/{processInstanceKey}/call-hierarchy",
			params: "processInstanceKey: string",
			returns: "Array<ProcessInstanceCallHierarchyEntry",
		},
		cancelProcessInstance: {
			description:
				"Cancel process instance Cancels a running process instance. As a cancellation includes more than just the removal of the process instance resource, the cancellation resource must be posted.",
			endpoint: "POST /process-instances/{processInstanceKey}/cancellation",
			params: "processInstanceKey: string, body?: CancelProcessInstanceRequest",
			returns: "void",
		},
		deleteProcessInstance: {
			description:
				"Delete process instance Deletes a process instance. Only instances that are completed or terminated can be deleted.",
			endpoint: "POST /process-instances/{processInstanceKey}/deletion",
			params: "processInstanceKey: string, body?: DeleteProcessInstanceRequest",
			returns: "void",
		},
		resolveProcessInstanceIncidents: {
			description:
				"Resolve related incidents Creates a batch operation to resolve multiple incidents of a process instance.",
			endpoint: "POST /process-instances/{processInstanceKey}/incident-resolution",
			params: "processInstanceKey: string",
			returns: "BatchOperationCreatedResult",
		},
		searchProcessInstanceIncidents: {
			description:
				"Search related incidents Search for incidents caused by the process instance or any of its called process or decision instances. Although the `processInstanceKey` is provided as a path parameter to indicate the root process instance,",
			endpoint: "POST /process-instances/{processInstanceKey}/incidents/search",
			params: "processInstanceKey: string, body?: IncidentSearchQuery",
			returns: "IncidentSearchQueryResult",
		},
		migrateProcessInstance: {
			description:
				"Migrate process instance Migrates a process instance to a new process definition. This request can contain multiple mapping instructions to define mapping between the active process instance's elements and target process definition elements.",
			endpoint: "POST /process-instances/{processInstanceKey}/migration",
			params: "processInstanceKey: string, body: ProcessInstanceMigrationInstruction",
			returns: "void",
		},
		modifyProcessInstance: {
			description:
				"Modify process instance Modifies a running process instance. This request can contain multiple instructions to activate an element of the process or to terminate an active instance of an element.",
			endpoint: "POST /process-instances/{processInstanceKey}/modification",
			params: "processInstanceKey: string, body: ProcessInstanceModificationInstruction",
			returns: "void",
		},
		getProcessInstanceSequenceFlows: {
			description: "Get sequence flows Get sequence flows taken by the process instance.",
			endpoint: "GET /process-instances/{processInstanceKey}/sequence-flows",
			params: "processInstanceKey: string",
			returns: "ProcessInstanceSequenceFlowsQueryResult",
		},
		getProcessInstanceStatistics: {
			description:
				"Get element instance statistics Get statistics about elements by the process instance key.",
			endpoint: "GET /process-instances/{processInstanceKey}/statistics/element-instances",
			params: "processInstanceKey: string",
			returns: "ProcessInstanceElementStatisticsQueryResult",
		},
	},
	role: {
		createRole: {
			description: "Create role Create a new role.",
			endpoint: "POST /roles",
			params: "body?: RoleCreateRequest",
			returns: "RoleCreateResult",
		},
		searchRoles: {
			description: "Search roles Search for roles based on given criteria.",
			endpoint: "POST /roles/search",
			params: "body?: RoleSearchQueryRequest",
			returns: "RoleSearchQueryResult",
		},
		getRole: {
			description: "Get role Get a role by its ID.",
			endpoint: "GET /roles/{roleId}",
			params: "roleId: string",
			returns: "RoleResult",
		},
		updateRole: {
			description: "Update role Update a role with the given ID.",
			endpoint: "PUT /roles/{roleId}",
			params: "roleId: string, body: RoleUpdateRequest",
			returns: "RoleUpdateResult",
		},
		deleteRole: {
			description: "Delete role Deletes the role with the given ID.",
			endpoint: "DELETE /roles/{roleId}",
			params: "roleId: string",
			returns: "void",
		},
		searchClientsForRole: {
			description: "Search role clients Search clients with assigned role.",
			endpoint: "POST /roles/{roleId}/clients/search",
			params: "roleId: string, body?: RoleClientSearchQueryRequest",
			returns: "RoleClientSearchResult",
		},
		assignRoleToClient: {
			description:
				"Assign a role to a client Assigns the specified role to the client. The client will inherit the authorizations associated with this role.",
			endpoint: "PUT /roles/{roleId}/clients/{clientId}",
			params: "roleId: string, clientId: string",
			returns: "void",
		},
		unassignRoleFromClient: {
			description:
				"Unassign a role from a client Unassigns the specified role from the client. The client will no longer inherit the authorizations associated with this role.",
			endpoint: "DELETE /roles/{roleId}/clients/{clientId}",
			params: "roleId: string, clientId: string",
			returns: "void",
		},
		searchGroupsForRole: {
			description: "Search role groups Search groups with assigned role.",
			endpoint: "POST /roles/{roleId}/groups/search",
			params: "roleId: string, body?: RoleGroupSearchQueryRequest",
			returns: "RoleGroupSearchResult",
		},
		assignRoleToGroup: {
			description:
				"Assign a role to a group Assigns the specified role to the group. Every member of the group (user or client) will inherit the authorizations associated with this role.",
			endpoint: "PUT /roles/{roleId}/groups/{groupId}",
			params: "roleId: string, groupId: string",
			returns: "void",
		},
		unassignRoleFromGroup: {
			description:
				"Unassign a role from a group Unassigns the specified role from the group. All group members (user or client) no longer inherit the authorizations associated with this role.",
			endpoint: "DELETE /roles/{roleId}/groups/{groupId}",
			params: "roleId: string, groupId: string",
			returns: "void",
		},
		searchMappingRulesForRole: {
			description: "Search role mapping rules Search mapping rules with assigned role.",
			endpoint: "POST /roles/{roleId}/mapping-rules/search",
			params: "roleId: string, body?: MappingRuleSearchQueryRequest",
			returns: "RoleMappingRuleSearchResult",
		},
		assignRoleToMappingRule: {
			description: "Assign a role to a mapping rule Assigns a role to a mapping rule.",
			endpoint: "PUT /roles/{roleId}/mapping-rules/{mappingRuleId}",
			params: "roleId: string, mappingRuleId: string",
			returns: "void",
		},
		unassignRoleFromMappingRule: {
			description: "Unassign a role from a mapping rule Unassigns a role from a mapping rule.",
			endpoint: "DELETE /roles/{roleId}/mapping-rules/{mappingRuleId}",
			params: "roleId: string, mappingRuleId: string",
			returns: "void",
		},
		searchUsersForRole: {
			description: "Search role users Search users with assigned role.",
			endpoint: "POST /roles/{roleId}/users/search",
			params: "roleId: string, body?: RoleUserSearchQueryRequest",
			returns: "RoleUserSearchResult",
		},
		assignRoleToUser: {
			description:
				"Assign a role to a user Assigns the specified role to the user. The user will inherit the authorizations associated with this role.",
			endpoint: "PUT /roles/{roleId}/users/{username}",
			params: "roleId: string, username: string",
			returns: "void",
		},
		unassignRoleFromUser: {
			description:
				"Unassign a role from a user Unassigns a role from a user. The user will no longer inherit the authorizations associated with this role.",
			endpoint: "DELETE /roles/{roleId}/users/{username}",
			params: "roleId: string, username: string",
			returns: "void",
		},
	},
	setup: {
		createAdminUser: {
			description:
				"Create admin user Creates a new user and assigns the admin role to it. This endpoint is only usable when users are managed in the Orchestration Cluster and while no user is assigned to the admin role.",
			endpoint: "POST /setup/user",
			params: "body: UserRequest",
			returns: "UserCreateResult",
		},
	},
	signal: {
		broadcastSignal: {
			description: "Broadcast signal Broadcasts a signal.",
			endpoint: "POST /signals/broadcast",
			params: "body: SignalBroadcastRequest",
			returns: "SignalBroadcastResult",
		},
	},
	cluster: {
		getStatus: {
			description:
				"Get cluster status Checks the health status of the cluster by verifying if there's at least one partition with a healthy leader.",
			endpoint: "GET /status",
			params: "none",
			returns: "void",
		},
		getTopology: {
			description:
				"Get cluster topology Obtains the current topology of the cluster the gateway is part of.",
			endpoint: "GET /topology",
			params: "none",
			returns: "TopologyResponse",
		},
	},
	system: {
		getUsageMetrics: {
			description: "Get usage metrics Retrieve the usage metrics based on given criteria.",
			endpoint: "GET /system/usage-metrics",
			params:
				"query?: { startTime: string; endTime: string; tenantId?: TenantId; withTenants?: boolean }",
			returns: "UsageMetricsResponse",
		},
	},
	tenant: {
		createTenant: {
			description: "Create tenant Creates a new tenant.",
			endpoint: "POST /tenants",
			params: "body: TenantCreateRequest",
			returns: "TenantCreateResult",
		},
		searchTenants: {
			description: "Search tenants Retrieves a filtered and sorted list of tenants.",
			endpoint: "POST /tenants/search",
			params: "body?: TenantSearchQueryRequest",
			returns: "TenantSearchQueryResult",
		},
		getTenant: {
			description: "Get tenant Retrieves a single tenant by tenant ID.",
			endpoint: "GET /tenants/{tenantId}",
			params: "tenantId: string",
			returns: "TenantResult",
		},
		updateTenant: {
			description: "Update tenant Updates an existing tenant.",
			endpoint: "PUT /tenants/{tenantId}",
			params: "tenantId: string, body: TenantUpdateRequest",
			returns: "TenantUpdateResult",
		},
		deleteTenant: {
			description: "Delete tenant Deletes an existing tenant.",
			endpoint: "DELETE /tenants/{tenantId}",
			params: "tenantId: string",
			returns: "void",
		},
		searchClientsForTenant: {
			description:
				"Search clients for tenant Retrieves a filtered and sorted list of clients for a specified tenant.",
			endpoint: "POST /tenants/{tenantId}/clients/search",
			params: "tenantId: string, body?: TenantClientSearchQueryRequest",
			returns: "TenantClientSearchResult",
		},
		assignClientToTenant: {
			description:
				"Assign a client to a tenant Assign the client to the specified tenant. The client can then access tenant data and perform authorized actions.",
			endpoint: "PUT /tenants/{tenantId}/clients/{clientId}",
			params: "tenantId: string, clientId: string",
			returns: "void",
		},
		unassignClientFromTenant: {
			description:
				"Unassign a client from a tenant Unassigns the client from the specified tenant. The client can no longer access tenant data.",
			endpoint: "DELETE /tenants/{tenantId}/clients/{clientId}",
			params: "tenantId: string, clientId: string",
			returns: "void",
		},
		searchGroupIdsForTenant: {
			description:
				"Search groups for tenant Retrieves a filtered and sorted list of groups for a specified tenant.",
			endpoint: "POST /tenants/{tenantId}/groups/search",
			params: "tenantId: string, body?: TenantGroupSearchQueryRequest",
			returns: "TenantGroupSearchResult",
		},
		assignGroupToTenant: {
			description:
				"Assign a group to a tenant Assigns a group to a specified tenant. Group members (users, clients) can then access tenant data and perform authorized actions.",
			endpoint: "PUT /tenants/{tenantId}/groups/{groupId}",
			params: "tenantId: string, groupId: string",
			returns: "void",
		},
		unassignGroupFromTenant: {
			description:
				"Unassign a group from a tenant Unassigns a group from a specified tenant. Members of the group (users, clients) will no longer have access to the tenant's data - except they are assigned directly to the tenant.",
			endpoint: "DELETE /tenants/{tenantId}/groups/{groupId}",
			params: "tenantId: string, groupId: string",
			returns: "void",
		},
		searchMappingRulesForTenant: {
			description:
				"Search mapping rules for tenant Retrieves a filtered and sorted list of MappingRules for a specified tenant.",
			endpoint: "POST /tenants/{tenantId}/mapping-rules/search",
			params: "tenantId: string, body?: MappingRuleSearchQueryRequest",
			returns: "TenantMappingRuleSearchResult",
		},
		assignMappingRuleToTenant: {
			description:
				"Assign a mapping rule to a tenant Assign a single mapping rule to a specified tenant.",
			endpoint: "PUT /tenants/{tenantId}/mapping-rules/{mappingRuleId}",
			params: "tenantId: string, mappingRuleId: string",
			returns: "void",
		},
		unassignMappingRuleFromTenant: {
			description:
				"Unassign a mapping rule from a tenant Unassigns a single mapping rule from a specified tenant without deleting the rule.",
			endpoint: "DELETE /tenants/{tenantId}/mapping-rules/{mappingRuleId}",
			params: "tenantId: string, mappingRuleId: string",
			returns: "void",
		},
		searchRolesForTenant: {
			description:
				"Search roles for tenant Retrieves a filtered and sorted list of roles for a specified tenant.",
			endpoint: "POST /tenants/{tenantId}/roles/search",
			params: "tenantId: string, body?: RoleSearchQueryRequest",
			returns: "TenantRoleSearchResult",
		},
		assignRoleToTenant: {
			description:
				"Assign a role to a tenant Assigns a role to a specified tenant. Users, Clients or Groups, that have the role assigned, will get access to the tenant's data and can perform actions according to their authorizations.",
			endpoint: "PUT /tenants/{tenantId}/roles/{roleId}",
			params: "tenantId: string, roleId: string",
			returns: "void",
		},
		unassignRoleFromTenant: {
			description:
				"Unassign a role from a tenant Unassigns a role from a specified tenant. Users, Clients or Groups, that have the role assigned, will no longer have access to the tenant's data - unless they are assigned directly to the tenant.",
			endpoint: "DELETE /tenants/{tenantId}/roles/{roleId}",
			params: "tenantId: string, roleId: string",
			returns: "void",
		},
		searchUsersForTenant: {
			description:
				"Search users for tenant Retrieves a filtered and sorted list of users for a specified tenant.",
			endpoint: "POST /tenants/{tenantId}/users/search",
			params: "tenantId: string, body?: TenantUserSearchQueryRequest",
			returns: "TenantUserSearchResult",
		},
		assignUserToTenant: {
			description:
				"Assign a user to a tenant Assign a single user to a specified tenant. The user can then access tenant data and perform authorized actions.",
			endpoint: "PUT /tenants/{tenantId}/users/{username}",
			params: "tenantId: string, username: string",
			returns: "void",
		},
		unassignUserFromTenant: {
			description:
				"Unassign a user from a tenant Unassigns the user from the specified tenant. The user can no longer access tenant data.",
			endpoint: "DELETE /tenants/{tenantId}/users/{username}",
			params: "tenantId: string, username: string",
			returns: "void",
		},
	},
	user: {
		createUser: {
			description: "Create user Create a new user.",
			endpoint: "POST /users",
			params: "body: UserRequest",
			returns: "UserCreateResult",
		},
		searchUsers: {
			description: "Search users Search for users based on given criteria.",
			endpoint: "POST /users/search",
			params: "body?: UserSearchQueryRequest",
			returns: "UserSearchResult",
		},
		getUser: {
			description: "Get user Get a user by its username.",
			endpoint: "GET /users/{username}",
			params: "username: string",
			returns: "UserResult",
		},
		updateUser: {
			description: "Update user Updates a user.",
			endpoint: "PUT /users/{username}",
			params: "username: string, body: UserUpdateRequest",
			returns: "UserUpdateResult",
		},
		deleteUser: {
			description: "Delete user Deletes a user.",
			endpoint: "DELETE /users/{username}",
			params: "username: string",
			returns: "void",
		},
	},
	userTask: {
		searchUserTasks: {
			description: "Search user tasks Search for user tasks based on given criteria.",
			endpoint: "POST /user-tasks/search",
			params: "body?: UserTaskSearchQuery",
			returns: "UserTaskSearchQueryResult",
		},
		getUserTask: {
			description: "Get user task Get the user task by the user task key.",
			endpoint: "GET /user-tasks/{userTaskKey}",
			params: "userTaskKey: string",
			returns: "UserTaskResult",
		},
		updateUserTask: {
			description: "Update user task Update a user task with the given key.",
			endpoint: "PATCH /user-tasks/{userTaskKey}",
			params: "userTaskKey: string, body?: UserTaskUpdateRequest",
			returns: "void",
		},
		unassignUserTask: {
			description: "Unassign user task Removes the assignee of a task with the given key.",
			endpoint: "DELETE /user-tasks/{userTaskKey}/assignee",
			params: "userTaskKey: string",
			returns: "void",
		},
		assignUserTask: {
			description: "Assign user task Assigns a user task with the given key to the given assignee.",
			endpoint: "POST /user-tasks/{userTaskKey}/assignment",
			params: "userTaskKey: string, body: UserTaskAssignmentRequest",
			returns: "void",
		},
		searchUserTaskAuditLogs: {
			description:
				"Search user task audit logs Search for user task audit logs based on given criteria.",
			endpoint: "POST /user-tasks/{userTaskKey}/audit-logs/search",
			params: "userTaskKey: string, body?: UserTaskAuditLogSearchQueryRequest",
			returns: "AuditLogSearchQueryResult",
		},
		completeUserTask: {
			description: "Complete user task Completes a user task with the given key.",
			endpoint: "POST /user-tasks/{userTaskKey}/completion",
			params: "userTaskKey: string, body?: UserTaskCompletionRequest",
			returns: "void",
		},
		getUserTaskForm: {
			description:
				"Get user task form Get the form of a user task. Note that this endpoint will only return linked forms. This endpoint does not support embedded forms.",
			endpoint: "GET /user-tasks/{userTaskKey}/form",
			params: "userTaskKey: string",
			returns: "FormResult",
		},
		searchUserTaskVariables: {
			description:
				"Search user task variables Search for user task variables based on given criteria. This endpoint returns all variables visible from the user task's scope, including variables from parent scopes in the scope hierarchy. By default, long variable values in the response are truncated.",
			endpoint: "POST /user-tasks/{userTaskKey}/variables/search",
			params:
				"userTaskKey: string, body?: UserTaskVariableSearchQueryRequest, query?: { truncateValues?: boolean }",
			returns: "VariableSearchQueryResult",
		},
	},
	variable: {
		searchVariables: {
			description:
				"Search variables Search for variables based on given criteria. This endpoint returns variables that exist directly at the specified scopes - it does not",
			endpoint: "POST /variables/search",
			params: "body?: VariableSearchQuery, query?: { truncateValues?: boolean }",
			returns: "VariableSearchQueryResult",
		},
		getVariable: {
			description:
				"Get variable Get a variable by its key. This endpoint returns both process-level and local (element-scoped) variables.",
			endpoint: "GET /variables/{variableKey}",
			params: "variableKey: string",
			returns: "VariableResult",
		},
	},
} as const
