/** Generates a self-contained dark-theme HTML report. */

const CSS = `
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: system-ui, -apple-system, sans-serif;
    background: #0d0d16;
    color: #cdd6f4;
    padding: 2rem;
    line-height: 1.5;
  }
  header { margin-bottom: 2rem; border-bottom: 1px solid #2a2a42; padding-bottom: 1rem; }
  h1 { font-size: 1.5rem; font-weight: 600; color: #6b9df7; }
  .meta { font-size: 0.85rem; color: #8888a8; margin-top: 0.25rem; }
  .summary {
    display: flex; gap: 1rem; flex-wrap: wrap;
    margin-bottom: 2rem;
  }
  .stat {
    background: #161626;
    border: 1px solid #2a2a42;
    border-radius: 6px;
    padding: 0.75rem 1.25rem;
    min-width: 140px;
  }
  .stat-label { font-size: 0.75rem; color: #8888a8; text-transform: uppercase; letter-spacing: 0.05em; }
  .stat-value { font-size: 1.75rem; font-weight: 700; margin-top: 0.2rem; }
  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.875rem;
  }
  thead th {
    background: #1e1e2e;
    color: #8888a8;
    font-weight: 600;
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    padding: 0.6rem 0.75rem;
    text-align: left;
    border-bottom: 1px solid #2a2a42;
  }
  tbody tr { border-bottom: 1px solid #2a2a42; }
  tbody tr:last-child { border-bottom: none; }
  tbody tr:hover { background: #161626; }
  tbody td { padding: 0.6rem 0.75rem; vertical-align: top; }
  .badge {
    display: inline-block;
    padding: 0.15rem 0.5rem;
    border-radius: 4px;
    font-size: 0.75rem;
    font-weight: 600;
  }
  .badge-active { background: rgba(248,113,113,0.15); color: #f87171; }
  .badge-resolved { background: rgba(34,197,94,0.15); color: #22c55e; }
  .badge-running { background: rgba(107,157,247,0.15); color: #6b9df7; }
  .badge-completed { background: rgba(34,197,94,0.15); color: #22c55e; }
  .badge-canceled { background: rgba(136,136,168,0.15); color: #8888a8; }
  .badge-breached { background: rgba(245,158,11,0.15); color: #f59e0b; }
  .badge-ok { background: rgba(34,197,94,0.15); color: #22c55e; }
  .key { font-family: ui-monospace, "Cascadia Code", monospace; font-size: 0.8rem; color: #8888a8; }
  footer { margin-top: 2rem; font-size: 0.8rem; color: #8888a8; border-top: 1px solid #2a2a42; padding-top: 1rem; }
`

export interface ReportColumn {
	header: string
	render: (row: unknown) => string
	isHtml?: boolean
}

export function buildReport(opts: {
	title: string
	subtitle?: string
	stats: { label: string; value: string | number; color?: string }[]
	columns: ReportColumn[]
	rows: unknown[]
}): string {
	const now = new Date().toLocaleString()

	const statCards = opts.stats
		.map((s) => {
			const color = s.color ? `color: ${s.color};` : ""
			return `<div class="stat"><div class="stat-label">${s.label}</div><div class="stat-value" style="${color}">${s.value}</div></div>`
		})
		.join("\n")

	const thead = opts.columns.map((c) => `<th>${c.header}</th>`).join("")

	const tbody = opts.rows
		.map((row) => {
			const cells = opts.columns
				.map((c) => `<td>${c.isHtml ? c.render(row) : esc(c.render(row))}</td>`)
				.join("")
			return `<tr>${cells}</tr>`
		})
		.join("\n")

	return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(opts.title)}</title>
<style>${CSS}</style>
</head>
<body>
<header>
  <h1>${esc(opts.title)}</h1>
  ${opts.subtitle ? `<div class="meta">${esc(opts.subtitle)}</div>` : ""}
  <div class="meta">Generated ${now}</div>
</header>
<div class="summary">
${statCards}
</div>
<table>
  <thead><tr>${thead}</tr></thead>
  <tbody>
${tbody}
  </tbody>
</table>
<footer>Generated by casen-report &bull; bpmnkit.com</footer>
</body>
</html>`
}

function esc(s: string): string {
	return s
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;")
}

export function badge(text: string, cls: string): string {
	return `<span class="badge badge-${cls}">${text}</span>`
}
